class SignupCountry {
  const SignupCountry(this.name, this.iso, this.dial);
  final String name;
  final String iso;
  final String dial;

  String get flag {
    if (iso.length != 2) return '';
    final a = iso.codeUnitAt(0) - 0x41 + 0x1F1E6;
    final b = iso.codeUnitAt(1) - 0x41 + 0x1F1E6;
    return String.fromCharCodes([a, b]);
  }
}

/// Same country set the CRM portal signup picker uses.
const signupCountries = <SignupCountry>[
  SignupCountry('Afghanistan', 'AF', '93'),
  SignupCountry('Albania', 'AL', '355'),
  SignupCountry('Algeria', 'DZ', '213'),
  SignupCountry('Andorra', 'AD', '376'),
  SignupCountry('Angola', 'AO', '244'),
  SignupCountry('Argentina', 'AR', '54'),
  SignupCountry('Armenia', 'AM', '374'),
  SignupCountry('Australia', 'AU', '61'),
  SignupCountry('Austria', 'AT', '43'),
  SignupCountry('Azerbaijan', 'AZ', '994'),
  SignupCountry('Bahrain', 'BH', '973'),
  SignupCountry('Bangladesh', 'BD', '880'),
  SignupCountry('Belarus', 'BY', '375'),
  SignupCountry('Belgium', 'BE', '32'),
  SignupCountry('Bhutan', 'BT', '975'),
  SignupCountry('Brazil', 'BR', '55'),
  SignupCountry('Bulgaria', 'BG', '359'),
  SignupCountry('Cambodia', 'KH', '855'),
  SignupCountry('Cameroon', 'CM', '237'),
  SignupCountry('Canada', 'CA', '1'),
  SignupCountry('Chile', 'CL', '56'),
  SignupCountry('China', 'CN', '86'),
  SignupCountry('Colombia', 'CO', '57'),
  SignupCountry('Croatia', 'HR', '385'),
  SignupCountry('Cyprus', 'CY', '357'),
  SignupCountry('Czech Republic', 'CZ', '420'),
  SignupCountry('Denmark', 'DK', '45'),
  SignupCountry('Egypt', 'EG', '20'),
  SignupCountry('Estonia', 'EE', '372'),
  SignupCountry('Ethiopia', 'ET', '251'),
  SignupCountry('Finland', 'FI', '358'),
  SignupCountry('France', 'FR', '33'),
  SignupCountry('Georgia', 'GE', '995'),
  SignupCountry('Germany', 'DE', '49'),
  SignupCountry('Ghana', 'GH', '233'),
  SignupCountry('Greece', 'GR', '30'),
  SignupCountry('Hong Kong', 'HK', '852'),
  SignupCountry('Hungary', 'HU', '36'),
  SignupCountry('India', 'IN', '91'),
  SignupCountry('Indonesia', 'ID', '62'),
  SignupCountry('Iran', 'IR', '98'),
  SignupCountry('Iraq', 'IQ', '964'),
  SignupCountry('Ireland', 'IE', '353'),
  SignupCountry('Israel', 'IL', '972'),
  SignupCountry('Italy', 'IT', '39'),
  SignupCountry('Japan', 'JP', '81'),
  SignupCountry('Jordan', 'JO', '962'),
  SignupCountry('Kazakhstan', 'KZ', '7'),
  SignupCountry('Kenya', 'KE', '254'),
  SignupCountry('Kuwait', 'KW', '965'),
  SignupCountry('Lebanon', 'LB', '961'),
  SignupCountry('Libya', 'LY', '218'),
  SignupCountry('Lithuania', 'LT', '370'),
  SignupCountry('Luxembourg', 'LU', '352'),
  SignupCountry('Malaysia', 'MY', '60'),
  SignupCountry('Maldives', 'MV', '960'),
  SignupCountry('Malta', 'MT', '356'),
  SignupCountry('Mexico', 'MX', '52'),
  SignupCountry('Moldova', 'MD', '373'),
  SignupCountry('Monaco', 'MC', '377'),
  SignupCountry('Morocco', 'MA', '212'),
  SignupCountry('Myanmar', 'MM', '95'),
  SignupCountry('Nepal', 'NP', '977'),
  SignupCountry('Netherlands', 'NL', '31'),
  SignupCountry('New Zealand', 'NZ', '64'),
  SignupCountry('Nigeria', 'NG', '234'),
  SignupCountry('Norway', 'NO', '47'),
  SignupCountry('Oman', 'OM', '968'),
  SignupCountry('Pakistan', 'PK', '92'),
  SignupCountry('Philippines', 'PH', '63'),
  SignupCountry('Poland', 'PL', '48'),
  SignupCountry('Portugal', 'PT', '351'),
  SignupCountry('Qatar', 'QA', '974'),
  SignupCountry('Romania', 'RO', '40'),
  SignupCountry('Russia', 'RU', '7'),
  SignupCountry('Saudi Arabia', 'SA', '966'),
  SignupCountry('Singapore', 'SG', '65'),
  SignupCountry('South Africa', 'ZA', '27'),
  SignupCountry('South Korea', 'KR', '82'),
  SignupCountry('Spain', 'ES', '34'),
  SignupCountry('Sri Lanka', 'LK', '94'),
  SignupCountry('Sweden', 'SE', '46'),
  SignupCountry('Switzerland', 'CH', '41'),
  SignupCountry('Taiwan', 'TW', '886'),
  SignupCountry('Tanzania', 'TZ', '255'),
  SignupCountry('Thailand', 'TH', '66'),
  SignupCountry('Tunisia', 'TN', '216'),
  SignupCountry('Turkey', 'TR', '90'),
  SignupCountry('Ukraine', 'UA', '380'),
  SignupCountry('United Arab Emirates', 'AE', '971'),
  SignupCountry('United Kingdom', 'GB', '44'),
  SignupCountry('United States', 'US', '1'),
  SignupCountry('Uruguay', 'UY', '598'),
  SignupCountry('Uzbekistan', 'UZ', '998'),
  SignupCountry('Vietnam', 'VN', '84'),
  SignupCountry('Yemen', 'YE', '967'),
];
