# Generated by Django 6.0.5 on 2026-05-07 18:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, default='', help_text='SMTP server hostname (e.g. smtp.gmail.com).', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='SMTP port (587 for TLS, 465 for SSL, 25 for none).')),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password_encrypted', models.TextField(blank=True, default='', help_text='Fernet-encrypted SMTP password. Use set_password() / get_password().')),
                ('encryption_type', models.CharField(choices=[('NONE', 'None'), ('SSL', 'SSL'), ('TLS', 'TLS')], default='TLS', max_length=4)),
                ('from_email', models.EmailField(blank=True, default='', help_text='Sender email address (the "From" field).', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', help_text='Display name for outgoing emails (e.g. "Burjex Prime").', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Master switch: disable to stop all outgoing notification emails.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email notification settings',
                'verbose_name_plural': 'Email notification settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(help_text='Supports {{variable}} placeholders (e.g. {{company_name}}).', max_length=255)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('TRADING', 'Trading'), ('IB', 'Introducing Broker'), ('SUPPORT', 'Support'), ('MARKETING', 'Marketing')], db_index=True, default='AUTH', max_length=20)),
                ('event_key', models.SlugField(help_text='Unique key used to trigger this template (e.g. welcome_email, deposit_confirmation).', max_length=80, unique=True)),
                ('html_content', models.TextField(help_text='HTML body with {{variable}} placeholders. Available: {{user_name}}, {{user_email}}, {{otp}}, {{amount}}, {{company_name}}, {{reason}}, {{date}}, {{verify_url}}, etc.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification template',
                'verbose_name_plural': 'Notification templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('event_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('OPENED', 'Opened')], db_index=True, default='QUEUED', max_length=10)),
                ('error_details', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='email_notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification log',
                'verbose_name_plural': 'Notification logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='email_notif_recipie_6759fb_idx'), models.Index(fields=['-created_at'], name='email_notif_created_5f8a23_idx')],
            },
        ),
    ]
