# Generated by Django 6.0.3 on 2026-03-30 12:13

import django.db.models.deletion
import live_chat.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_tone', models.CharField(default='warm', max_length=40)),
                ('max_response_length', models.PositiveIntegerField(default=400)),
                ('creativity_temperature', models.DecimalField(decimal_places=2, default=0.3, max_digits=3)),
                ('include_user_info', models.BooleanField(default=True)),
                ('include_page_url', models.BooleanField(default=True)),
                ('recent_messages_count', models.PositiveIntegerField(default=10)),
                ('system_role', models.CharField(default='Support assistant', max_length=120)),
                ('ai_instructions', models.TextField(default='Friendly responses. Concise replies. Warm tone. Helpful responses. Ask questions when needed.')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_ai_settings',
            },
        ),
        migrations.CreateModel(
            name='ChatBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('mon_enabled', models.BooleanField(default=True)),
                ('tue_enabled', models.BooleanField(default=True)),
                ('wed_enabled', models.BooleanField(default=True)),
                ('thu_enabled', models.BooleanField(default=True)),
                ('fri_enabled', models.BooleanField(default=True)),
                ('sat_enabled', models.BooleanField(default=False)),
                ('sun_enabled', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('offline_detection', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_business_hours',
            },
        ),
        migrations.CreateModel(
            name='ChatNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_chat_sound', models.BooleanField(default=True)),
                ('new_message_sound', models.BooleanField(default=True)),
                ('volume_percent', models.PositiveIntegerField(default=80)),
                ('enable_browser_notifications', models.BooleanField(default=True)),
                ('agent_online_alert', models.BooleanField(default=True)),
                ('agent_offline_alert', models.BooleanField(default=True)),
                ('queue_threshold_alert', models.BooleanField(default=True)),
                ('queue_threshold_number', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_notifications',
            },
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_live_chat', models.BooleanField(default=True)),
                ('show_on_public_pages', models.BooleanField(default=True)),
                ('auto_assign_conversations', models.BooleanField(default=True)),
                ('enable_attachments', models.BooleanField(default=True)),
                ('show_typing_indicator', models.BooleanField(default=True)),
                ('missed_chat_timeout_seconds', models.PositiveIntegerField(default=120)),
                ('idle_timeout_seconds', models.PositiveIntegerField(default=300)),
                ('max_concurrent_chats', models.PositiveIntegerField(default=10)),
                ('enable_welcome_message', models.BooleanField(default=True)),
                ('welcome_message_text', models.TextField(blank=True, default='Hi! Welcome. How can we help you today?')),
                ('welcome_delay_seconds', models.PositiveIntegerField(default=2)),
                ('enable_offline_message', models.BooleanField(default=True)),
                ('offline_message_text', models.TextField(blank=True, default='We are offline right now. Please leave a message.')),
                ('collect_email_when_offline', models.BooleanField(default=True)),
                ('away_message_text', models.TextField(blank=True, default='Our agents are away. We will reply shortly.')),
                ('end_message_text', models.TextField(blank=True, default='Thanks for chatting with us.')),
                ('widget_color', models.CharField(default='#0B3C5D', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('widget_position', models.CharField(default='BOTTOM_RIGHT', max_length=20)),
                ('custom_position_css', models.CharField(blank=True, default='', max_length=255)),
                ('button_size_px', models.PositiveIntegerField(default=56)),
                ('offset_x_px', models.PositiveIntegerField(default=24)),
                ('offset_y_px', models.PositiveIntegerField(default=24)),
                ('widget_title', models.CharField(default='Live Chat', max_length=120)),
                ('widget_subtitle', models.CharField(default='Chat with our support team', max_length=255)),
                ('show_agent_photo', models.BooleanField(default=True)),
                ('auto_open', models.BooleanField(default=False)),
                ('show_on_mobile', models.BooleanField(default=True)),
                ('sound_notifications', models.BooleanField(default=True)),
                ('guest_info_collection', models.BooleanField(default=True)),
                ('conversation_persistence', models.BooleanField(default=True)),
                ('source_tracking', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_settings',
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slash_command', models.CharField(max_length=60, unique=True)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('GREETINGS', 'Greetings'), ('QUESTIONS', 'Questions'), ('RESPONSES', 'Responses'), ('CLOSING', 'Closing')], default='RESPONSES', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quick_replies',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChatAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('max_concurrent_chats', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_agents',
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('guest_name', models.CharField(blank=True, default='', max_length=120)),
                ('guest_email', models.CharField(blank=True, default='', max_length=255)),
                ('page_url', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(blank=True, default='website', max_length=80)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ACTIVE', 'Active'), ('MISSED', 'Missed'), ('CLOSED', 'Closed')], db_index=True, default='QUEUED', max_length=20)),
                ('is_ticket', models.BooleanField(default=False)),
                ('ticket_number', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('unread_for_admin', models.BooleanField(default=True)),
                ('unread_for_client', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='live_chat.chatagent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('GUEST', 'Guest'), ('CLIENT', 'Client'), ('AGENT', 'Agent'), ('AI', 'AI'), ('SYSTEM', 'System')], default='GUEST', max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=live_chat.models.chat_attachment_path)),
                ('is_typing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live_chat.chatconversation')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['id'],
            },
        ),
    ]
