# Generated by Django 6.0.3 on 2026-03-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsettings',
            name='widget_position',
            field=models.CharField(choices=[('BOTTOM_RIGHT', 'Bottom Right'), ('BOTTOM_LEFT', 'Bottom Left'), ('CUSTOM', 'Custom Position')], default='BOTTOM_RIGHT', max_length=20),
        ),
    ]
