# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


def seed_daily_hours(apps, schema_editor):
    ChatBusinessHours = apps.get_model("live_chat", "ChatBusinessHours")
    for row in ChatBusinessHours.objects.all():
        row.mon_start_time = row.start_time
        row.mon_end_time = row.end_time
        row.tue_start_time = row.start_time
        row.tue_end_time = row.end_time
        row.wed_start_time = row.start_time
        row.wed_end_time = row.end_time
        row.thu_start_time = row.start_time
        row.thu_end_time = row.end_time
        row.fri_start_time = row.start_time
        row.fri_end_time = row.end_time
        row.sat_start_time = row.start_time
        row.sat_end_time = row.end_time
        row.sun_start_time = row.start_time
        row.sun_end_time = row.end_time
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ("live_chat", "0002_alter_chatsettings_widget_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsettings",
            name="away_delay_seconds",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="embed_widget_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="enable_away_message",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="enable_end_message",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="end_delay_seconds",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="offline_delay_seconds",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="chataisettings",
            name="auto_suggest_replies",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chataisettings",
            name="knowledge_base",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="fri_end_time",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="fri_start_time",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="mon_end_time",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="mon_start_time",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="sat_end_time",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="sat_start_time",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="sun_end_time",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="sun_start_time",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="thu_end_time",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="thu_start_time",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="tue_end_time",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="tue_start_time",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="wed_end_time",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="chatbusinesshours",
            name="wed_start_time",
            field=models.TimeField(default="09:00"),
        ),
        migrations.RunPython(seed_daily_hours, migrations.RunPython.noop),
    ]

