# Generated by Django 5.2.14 on 2026-07-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0004_merge_20260401_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
    ]
