# Generated by Django 6.0.3 on 2026-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_my_accounts', models.BooleanField(default=True)),
                ('show_balance', models.BooleanField(default=True)),
                ('show_trading_accounts', models.BooleanField(default=True)),
                ('show_buttons', models.BooleanField(default=True)),
                ('show_profile_menu', models.BooleanField(default=True)),
                ('enable_deposit_button', models.BooleanField(default=True)),
                ('enable_withdraw_button', models.BooleanField(default=True)),
                ('enable_trade_button', models.BooleanField(default=True)),
                ('enable_open_new_account', models.BooleanField(default=True)),
                ('enable_real_demo_tabs', models.BooleanField(default=True)),
                ('enable_account_dropdown_menu', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
