# Generated by Django 6.0.3 on 2026-03-26 10:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_dashboardsettings_enable_deal_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='static/uploads/logo', location='D:\\forex_crm\\static\\uploads\\logo'), upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SidebarUISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_bg_color', models.CharField(default='#0B1E3A', max_length=30)),
                ('sidebar_text_color', models.CharField(default='#FFFFFF', max_length=30)),
                ('sidebar_hover_color', models.CharField(default='rgba(255,255,255,0.06)', max_length=60)),
                ('sidebar_active_color', models.CharField(default='rgba(255,255,255,0.10)', max_length=60)),
                ('sidebar_width', models.PositiveIntegerField(default=260)),
                ('font_size', models.PositiveIntegerField(default=14)),
                ('font_family', models.CharField(default='Inter, system-ui', max_length=120)),
                ('animation_enabled', models.BooleanField(default=True)),
                ('logo_size_px', models.PositiveIntegerField(default=34)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
