# Generated by Django 6.0.3 on 2026-03-26 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mt5account_account_label_mt5account_deposit_enabled_and_more'),
        ('admin_panel', '0003_brandingsettings_sidebaruisettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=80)),
                ('account_code', models.CharField(max_length=20, unique=True)),
                ('platform', models.CharField(choices=[('MT5', 'MT5'), ('MT4', 'MT4')], default='MT5', max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('USDT', 'USDT')], default='USD', max_length=10)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('max_leverage', models.PositiveIntegerField(default=500)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('spread_type', models.CharField(choices=[('RAW', 'Raw'), ('STANDARD', 'Standard'), ('CUSTOM', 'Custom')], default='STANDARD', max_length=20)),
                ('spread', models.CharField(blank=True, default='', max_length=50)),
                ('swap_free', models.BooleanField(default=False)),
                ('stop_out_level', models.PositiveIntegerField(default=30)),
                ('margin_call_level', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('leverage', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('admin_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_mt5_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_requests', to='accounts.mt5account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_account_requests', to=settings.AUTH_USER_MODEL)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='admin_panel.tradingaccounttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
