# Generated by Django 6.0.3 on 2026-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_tradingaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsettings',
            name='enforce_wallet_only_withdrawal',
            field=models.BooleanField(default=True),
        ),
    ]
