# Generated by Django 6.0.3 on 2026-03-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_bankfield_compliancesettings_cryptonetwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancesettings',
            name='address_allow_reupload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='address_lock_after_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='bank_lock_after_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='crypto_lock_after_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='enable_address_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='enable_bank_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='enable_crypto_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='enable_identity_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='identity_allow_multiple_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='identity_allow_reupload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='identity_lock_after_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='identity_require_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='show_bank_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='show_compliance_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='show_crypto_section',
            field=models.BooleanField(default=True),
        ),
    ]
