# Generated by Django 6.0.3 on 2026-03-27 03:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_compliancesettings_address_allow_reupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Burjex Prime', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='static/uploads/logo', location='D:\\forex_crm\\static\\uploads\\logo'), upload_to='')),
                ('primary_color', models.CharField(default='#0B3C5D', max_length=20)),
                ('secondary_color', models.CharField(default='#072A42', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_mode', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('HIDDEN', 'Hidden')], default='REQUIRED', max_length=10)),
                ('last_name_mode', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('HIDDEN', 'Hidden')], default='REQUIRED', max_length=10)),
                ('full_name_mode', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('HIDDEN', 'Hidden')], default='HIDDEN', max_length=10)),
                ('email_mode', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('HIDDEN', 'Hidden')], default='REQUIRED', max_length=10)),
                ('phone_mode', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('HIDDEN', 'Hidden')], default='REQUIRED', max_length=10)),
                ('password_mode', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('HIDDEN', 'Hidden')], default='REQUIRED', max_length=10)),
                ('country_mode', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('HIDDEN', 'Hidden')], default='OPTIONAL', max_length=10)),
                ('captcha_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
