# Generated by Django 6.0.3 on 2026-03-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_brandsettings_signupsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=True)),
                ('token_expiry_hours', models.PositiveIntegerField(default=24)),
                ('allow_resend', models.BooleanField(default=True)),
                ('email_template', models.TextField(default='Hello {{name}}\n\nPlease verify your email:\n\n{{verify_url}}\n\nThank you.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sender_name', models.CharField(blank=True, default='', max_length=120)),
                ('use_tls', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='signupsettings',
            name='address_mode',
            field=models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('HIDDEN', 'Hidden')], default='OPTIONAL', max_length=10),
        ),
    ]
