# Generated by Django 6.0.3 on 2026-03-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_statusbadgesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferTreasurySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_transfers_enabled', models.BooleanField(default=True)),
                ('internal_maintenance_mode', models.BooleanField(default=False)),
                ('internal_min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('internal_max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('internal_fee_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENT', 'Percentage')], default='FIXED', max_length=15)),
                ('internal_fee_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('internal_daily_limit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('internal_cooldown_minutes', models.PositiveIntegerField(default=0)),
                ('internal_processing_mode', models.CharField(choices=[('INSTANT', 'Instant'), ('MANUAL', 'Manual')], default='INSTANT', max_length=15)),
                ('p2p_enabled', models.BooleanField(default=True)),
                ('p2p_min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('p2p_max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('p2p_fee_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('p2p_daily_limit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('p2p_cooldown_minutes', models.PositiveIntegerField(default=0)),
                ('transfer_require_kyc', models.BooleanField(default=False)),
                ('transfer_require_2fa', models.BooleanField(default=False)),
                ('transfer_max_pending', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Transfer treasury settings',
            },
        ),
        migrations.CreateModel(
            name='WalletTreasurySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_system_enabled', models.BooleanField(default=True)),
                ('auto_create_wallet_on_registration', models.BooleanField(default=True)),
                ('allow_deposits_to_wallet', models.BooleanField(default=True)),
                ('wallet_min_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('wallet_max_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('wallet_deposit_maintenance', models.BooleanField(default=False)),
                ('allow_withdrawals_from_wallet', models.BooleanField(default=True)),
                ('wallet_min_withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('wallet_max_withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('wallet_daily_withdraw_limit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('wallet_withdraw_maintenance', models.BooleanField(default=False)),
                ('allow_wallet_to_trading', models.BooleanField(default=True)),
                ('allow_trading_to_wallet', models.BooleanField(default=True)),
                ('allow_p2p_transfers', models.BooleanField(default=True)),
                ('require_kyc_wallet_withdraw', models.BooleanField(default=False)),
                ('require_2fa_wallet_withdraw', models.BooleanField(default=False)),
                ('wallet_withdraw_cooldown_minutes', models.PositiveIntegerField(default=0)),
                ('wallet_max_pending_withdrawals', models.PositiveIntegerField(default=0)),
                ('show_wallet_dashboard', models.BooleanField(default=True)),
                ('wallet_in_total_balance', models.BooleanField(default=True)),
                ('show_wallet_sidebar', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Wallet treasury settings',
            },
        ),
        migrations.CreateModel(
            name='WhitelistTreasurySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_enabled', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Whitelist treasury settings',
            },
        ),
    ]
