# Generated by Django 6.0.3 on 2026-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_treasury_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPlatformIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('MT4', 'MetaTrader 4'), ('MT5', 'MetaTrader 5'), ('CTRADER', 'cTrader'), ('MATCH_TRADER', 'Match Trader'), ('TRADELOCKER', 'TradeLocker'), ('VERTEX_TRADER', 'Vertex Trader'), ('X9_TRADER', 'X9 Trader')], db_index=True, max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Pause integration without deleting credentials.')),
                ('api_key', models.TextField(blank=True, default='', help_text='From your integration provider.')),
                ('secret_key', models.TextField(blank=True, default='', help_text='Optional second credential.')),
                ('server_name', models.CharField(blank=True, default='', max_length=200)),
                ('api_server_url', models.URLField(blank=True, default='', max_length=500)),
                ('quick_notes', models.TextField(blank=True, default='', help_text='Shown in admin overview card.')),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes (admin only).')),
                ('status_message', models.CharField(blank=True, default='', help_text='Short line shown next to Quick Notes (e.g. connection hint).', max_length=255)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_detail', models.CharField(blank=True, default='', max_length=500)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trading platform integration',
                'verbose_name_plural': 'Trading platform integrations',
                'ordering': ['platform'],
            },
        ),
    ]
