# Generated by Django 6.0.3 on 2026-03-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_trading_platform_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingplatformintegration',
            name='api_server_url',
            field=models.CharField(blank=True, default='', help_text='Base URL for API or WebTrader (https://...).', max_length=500),
        ),
    ]
