# Generated by Django 6.0.3 on 2026-03-29 18:42

import pathlib

import django.core.files.storage
from django.db import migrations, models

_LOGO_DIR = pathlib.Path(__file__).resolve().parent.parent.parent / "static" / "uploads" / "logo"


def copy_brandsettings_to_auth_branding(apps, schema_editor):
    Old = apps.get_model("admin_panel", "BrandSettings")
    Admin = apps.get_model("admin_panel", "AdminAuthBrandingSettings")
    User = apps.get_model("admin_panel", "UserAuthBrandingSettings")
    old = Old.objects.first()
    if not old:
        Admin.objects.get_or_create(pk=1)
        User.objects.get_or_create(pk=1)
        return

    def push(target):
        target.company_name = getattr(old, "company_name", None) or "Burjex Prime"
        target.primary_color = getattr(old, "primary_color", None) or "#0B3C5D"
        target.secondary_color = getattr(old, "secondary_color", None) or "#072A42"
        target.button_color = getattr(old, "primary_color", None) or "#0B3C5D"
        target.panel_background_color = getattr(old, "login_bg_color", None) or "#0f172a"
        target.welcome_text = getattr(old, "welcome_text", None) or "Welcome Back"
        target.logo_size = getattr(old, "logo_size", None) or "medium"
        target.logo_position = getattr(old, "logo_position", None) or "center"
        try:
            target.logo_opacity = max(0.05, min(0.2, float(getattr(old, "logo_opacity", 0.1) or 0.1)))
        except (TypeError, ValueError):
            target.logo_opacity = 0.1
        try:
            if getattr(old, "logo", None) and getattr(old.logo, "name", None):
                target.logo = old.logo
        except Exception:
            pass
        try:
            if getattr(old, "login_logo", None) and getattr(old.login_logo, "name", None):
                target.background_logo = old.login_logo
        except Exception:
            pass
        target.save()

    a, _ = Admin.objects.get_or_create(pk=1)
    u, _ = User.objects.get_or_create(pk=1)
    push(a)
    push(u)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0020_brandsettings_unified_login_branding"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuthBrandingSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(default="Burjex Prime", max_length=120)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="static/uploads/logo",
                            location=str(_LOGO_DIR),
                        ),
                        upload_to="",
                    ),
                ),
                ("background_logo", models.FileField(blank=True, null=True, upload_to="branding/auth/admin")),
                ("primary_color", models.CharField(default="#0B3C5D", max_length=20)),
                ("secondary_color", models.CharField(default="#072A42", max_length=20)),
                ("button_color", models.CharField(default="#0B3C5D", max_length=20)),
                ("panel_background_color", models.CharField(default="#0f172a", max_length=32)),
                ("font_style", models.CharField(default="Inter, system-ui, sans-serif", max_length=200)),
                ("text_size_px", models.PositiveSmallIntegerField(default=14)),
                ("heading_size_px", models.PositiveSmallIntegerField(default=28)),
                ("welcome_text", models.CharField(default="Welcome Back", max_length=120)),
                (
                    "logo_size",
                    models.CharField(
                        choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "logo_position",
                    models.CharField(
                        choices=[("center", "Center"), ("left", "Left"), ("right", "Right")],
                        default="center",
                        max_length=16,
                    ),
                ),
                ("logo_opacity", models.FloatField(default=0.1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin auth branding",
                "verbose_name_plural": "Admin auth branding",
            },
        ),
        migrations.CreateModel(
            name="UserAuthBrandingSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(default="Burjex Prime", max_length=120)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="static/uploads/logo",
                            location=str(_LOGO_DIR),
                        ),
                        upload_to="",
                    ),
                ),
                ("background_logo", models.FileField(blank=True, null=True, upload_to="branding/auth/user")),
                ("primary_color", models.CharField(default="#0B3C5D", max_length=20)),
                ("secondary_color", models.CharField(default="#072A42", max_length=20)),
                ("button_color", models.CharField(default="#0B3C5D", max_length=20)),
                ("panel_background_color", models.CharField(default="#0f172a", max_length=32)),
                ("font_style", models.CharField(default="Inter, system-ui, sans-serif", max_length=200)),
                ("text_size_px", models.PositiveSmallIntegerField(default=14)),
                ("heading_size_px", models.PositiveSmallIntegerField(default=28)),
                ("welcome_text", models.CharField(default="Welcome Back", max_length=120)),
                (
                    "logo_size",
                    models.CharField(
                        choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "logo_position",
                    models.CharField(
                        choices=[("center", "Center"), ("left", "Left"), ("right", "Right")],
                        default="center",
                        max_length=16,
                    ),
                ),
                ("logo_opacity", models.FloatField(default=0.1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User auth branding",
                "verbose_name_plural": "User auth branding",
            },
        ),
        migrations.RunPython(copy_brandsettings_to_auth_branding, noop_reverse),
        migrations.DeleteModel(
            name="BrandSettings",
        ),
    ]
