# Generated by Django 6.0.3 on 2026-03-29 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_auth_branding_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCrmCommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_crm_lot_commission', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Broker CRM commission (testing)',
            },
        ),
        migrations.CreateModel(
            name='EmailSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email system settings',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('ib_request_approved', 'IB Request Approved'), ('ib_request_rejected', 'IB Request Rejected'), ('signup_welcome', 'Signup Welcome'), ('password_reset', 'Password Reset'), ('account_approved', 'Account Approved')], max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use variables: {{name}}, {{email}}, {{amount}}, {{reason}}, {{company_name}}, {{date}}, {{account_number}}')),
                ('send_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_key'],
            },
        ),
        migrations.CreateModel(
            name='SymbolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='allow_deposit_without_kyc',
            field=models.BooleanField(default=True, help_text='If disabled, clients need approved KYC before depositing.'),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='allow_ib_request_without_kyc',
            field=models.BooleanField(default=False, help_text='If enabled, clients may submit IB applications without approved KYC.'),
        ),
        migrations.AddField(
            model_name='compliancesettings',
            name='allow_withdraw_without_kyc',
            field=models.BooleanField(default=False, help_text='If enabled, clients may withdraw without approved identity+address KYC.'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.CreateModel(
            name='SimulatedIBTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=48)),
                ('lots', models.DecimalField(decimal_places=4, max_digits=14)),
                ('profit_per_lot', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('commission_per_lot_client', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('ib_commission_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('company_profit_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.tradingaccounttype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulated_trades_as_client', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulated_trades_created', to=settings.AUTH_USER_MODEL)),
                ('ib_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulated_trades_as_ib', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('display_name', models.CharField(blank=True, default='', max_length=160)),
                ('symbol_type', models.CharField(choices=[('FOREX', 'Forex'), ('METAL', 'Metal'), ('CRYPTO', 'Crypto'), ('INDICES', 'Indices')], default='FOREX', max_length=20)),
                ('suffix', models.CharField(blank=True, default='', help_text='Optional suffix for MT5 (e.g. .ecn). Stored separately from base code.', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symbols', to='admin_panel.symbolgroup')),
            ],
            options={
                'ordering': ['code', 'suffix'],
                'constraints': [models.UniqueConstraint(fields=('code', 'suffix'), name='uniq_tradingsymbol_code_suffix')],
            },
        ),
    ]
