# Generated by Django 6.0.3 on 2026-03-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_mt5group_account_type_mt5group_commission_per_lot_and_more'),
        ('admin_panel', '0022_kyc_email_symbols_ib_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccounttype',
            name='demo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='demo_expiry_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='demo_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_types_demo', to='accounts.mt5group'),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='demo_leverage',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='demo_platform_slug',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='demo_server_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='demo_symbol_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_types_demo', to='admin_panel.symbolgroup'),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='geographic_restrictions_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='account_types/icons'),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='inactivity_fee_after_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='inactivity_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='inactivity_fee_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='kyc_level',
            field=models.CharField(choices=[('NONE', 'None'), ('BASIC', 'Basic'), ('FULL', 'Full')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='live_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_types_live', to='accounts.mt5group'),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='live_leverage',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='live_platform_slug',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='live_server_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='live_symbol_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_types_live', to='admin_panel.symbolgroup'),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='maintenance_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='maintenance_fee_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='max_demo_accounts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='max_live_accounts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='max_single_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='max_total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='min_first_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='mt5_demo_series',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='mt5_live_series',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='require_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='require_id_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='require_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='settings_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
