# Generated by Django 6.0.3 on 2026-03-30 11:59

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_tradingaccounttype_demo_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAgreementsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, null=True, upload_to='legal/')),
                ('name', models.CharField(blank=True, default='Legal Agreements', max_length=140)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('terms_conditions_url', models.URLField(blank=True, default='')),
                ('privacy_policy_url', models.URLField(blank=True, default='')),
                ('client_agreement_url', models.URLField(blank=True, default='')),
                ('risk_disclosure_url', models.URLField(blank=True, default='')),
                ('aml_policy_url', models.URLField(blank=True, default='')),
                ('cookie_policy_url', models.URLField(blank=True, default='')),
                ('disclaimer_url', models.URLField(blank=True, default='')),
                ('bonus_credit_policy_url', models.URLField(blank=True, default='')),
                ('withdrawal_policy_url', models.URLField(blank=True, default='')),
                ('deposit_policy_url', models.URLField(blank=True, default='')),
                ('us_client_policy_url', models.URLField(blank=True, default='')),
                ('eu_uk_client_policy_url', models.URLField(blank=True, default='')),
                ('complaints_policy_url', models.URLField(blank=True, default='')),
                ('conflict_interest_policy_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(default='', editable=False, max_length=32, unique=True)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('application_name', models.CharField(blank=True, default='', max_length=140)),
                ('company_name', models.CharField(blank=True, default='Burjex Prime', max_length=160)),
                ('registration_number', models.CharField(blank=True, default='', max_length=120)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('primary_phone', models.CharField(blank=True, default='', max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='static/uploads/logo', location='D:\\forex_crm\\static\\uploads\\logo'), upload_to='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('client_area_url', models.URLField(blank=True, default='')),
                ('application_timezone', models.CharField(default='UTC', max_length=64)),
                ('business_license', models.CharField(blank=True, default='', max_length=180)),
                ('incorporation_country', models.CharField(blank=True, default='', max_length=120)),
                ('registered_address', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_icon', models.FileField(blank=True, null=True, upload_to='platforms/')),
                ('platform_name', models.CharField(default='MetaTrader 5', max_length=140)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('web_terminal_link', models.URLField(blank=True, default='')),
                ('ios_download_link', models.URLField(blank=True, default='')),
                ('android_download_link', models.URLField(blank=True, default='')),
                ('windows_download_link', models.URLField(blank=True, default='')),
                ('macos_download_link', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalCustomDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_documents', to='admin_panel.legalagreementssettings')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
