# Generated by Django 6.0.3 on 2026-03-30 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_legalagreementssettings_organizationprofilesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='api_version',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='broker_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='credentials',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='demo_manager_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='demo_network_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='download_android_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='download_ios_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='download_macos_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='download_windows_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='live_manager_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='live_network_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='network_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='payment_gateway_uuid',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tradingplatformintegration',
            name='web_terminal_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='loginbrandingsettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='tradingplatformintegration',
            name='platform',
            field=models.CharField(choices=[('MT5', 'MetaTrader 5'), ('CTRADER', 'cTrader'), ('MATCH_TRADER', 'Match Trader')], db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterModelTable(
            name='tradingplatformintegration',
            table='trading_platforms',
        ),
    ]
