# Generated by Django 6.0.3 on 2026-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_tradingplatformintegration_api_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginbrandingsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
