# Generated by Django 6.0.3 on 2026-03-30 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_alter_loginbrandingsettings_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SUMSUB', 'Sumsub'), ('ONFIDO', 'Onfido'), ('SHUFTI_PRO', 'Shufti Pro'), ('KYC_VERIFICATION', 'KYC Verification'), ('CUSTOM_API', 'Custom API')], max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('api_key', models.TextField(blank=True, default='')),
                ('secret_key', models.TextField(blank=True, default='')),
                ('webhook_url', models.CharField(blank=True, default='', max_length=500)),
                ('callback_url', models.CharField(blank=True, default='', max_length=500)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('LIVE', 'Live')], default='SANDBOX', max_length=10)),
                ('status_text', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance_integrations',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('AMAZON_SES', 'Amazon SES'), ('MAILGUN', 'Mailgun'), ('POSTMARK', 'Postmark'), ('SENDGRID', 'SendGrid'), ('ZEPTOMAIL', 'ZeptoMail'), ('SMTP_UNIVERSAL', 'SMTP Universal'), ('REOON', 'Reoon Email Verifier')], max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('api_key', models.TextField(blank=True, default='')),
                ('secret_key', models.TextField(blank=True, default='')),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sender_name', models.CharField(blank=True, default='', max_length=120)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.TextField(blank=True, default='')),
                ('encryption', models.CharField(default='TLS', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_providers',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='KYCStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('is_terminal', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'kyc_status',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('TWILIO_VERIFY', 'Twilio Verify'), ('TWILIO_WHATSAPP', 'Twilio WhatsApp'), ('CUSTOM_SMS_API', 'Custom SMS API')], max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('api_key', models.TextField(blank=True, default='')),
                ('sender_id', models.CharField(blank=True, default='', max_length=80)),
                ('api_url', models.CharField(blank=True, default='', max_length=500)),
                ('account_sid', models.CharField(blank=True, default='', max_length=255)),
                ('auth_token', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sms_providers',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='SupportIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('WHATSAPP_DIRECT', 'WhatsApp Direct'), ('LIVE_CHAT', 'Live Chat'), ('TAWK_TO', 'Tawk.to'), ('ZOHO_SALESIQ', 'Zoho SalesIQ'), ('EMAIL_SUPPORT', 'Email Support'), ('CUSTOM_API', 'Custom API Support')], max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('status', models.CharField(default='INACTIVE', max_length=10)),
                ('phone_number', models.CharField(blank=True, default='', max_length=40)),
                ('prefilled_message', models.TextField(blank=True, default='')),
                ('chat_bubble_icon', models.CharField(blank=True, default='', max_length=255)),
                ('chat_widget', models.TextField(blank=True, default='')),
                ('embed_code', models.TextField(blank=True, default='')),
                ('embed_script', models.TextField(blank=True, default='')),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('api_url', models.CharField(blank=True, default='', max_length=500)),
                ('token', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_integrations',
                'ordering': ['integration_type'],
            },
        ),
        migrations.CreateModel(
            name='SupportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floating_button_enabled', models.BooleanField(default=True)),
                ('floating_position', models.CharField(default='BOTTOM_RIGHT', max_length=20)),
                ('floating_icon', models.CharField(blank=True, default='', max_length=255)),
                ('default_ticket_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_settings',
            },
        ),
        migrations.CreateModel(
            name='ComplianceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('max_capacity', models.PositiveIntegerField(default=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_officer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_officers',
            },
        ),
        migrations.CreateModel(
            name='EmailProviderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('event_key', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='admin_panel.emailprovider')),
            ],
            options={
                'db_table': 'email_settings',
            },
        ),
        migrations.CreateModel(
            name='KYCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate')], default='INDIVIDUAL', max_length=20)),
                ('status', models.CharField(db_index=True, default='PENDING_REVIEW', max_length=30)),
                ('source', models.CharField(blank=True, default='PORTAL', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('partial_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_time_minutes', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='admin_panel.complianceofficer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, default='', max_length=80)),
                ('file_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.kycrequest')),
            ],
            options={
                'db_table': 'kyc_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='admin_panel.kycrequest')),
            ],
            options={
                'db_table': 'compliance_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('to_phone', models.CharField(max_length=40)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('event_key', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='admin_panel.smsprovider')),
            ],
            options={
                'db_table': 'sms_settings',
            },
        ),
        migrations.CreateModel(
            name='SupportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('status', models.CharField(default='OK', max_length=20)),
                ('payload', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.supportintegration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
