# Generated by Django 6.0.3 on 2026-03-31 13:08

import admin_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_emailsettings_event_template_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='demo_enabled',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='demo_expiry_days',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='demo_group',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='demo_leverage',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='demo_platform_slug',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='demo_server_name',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='demo_symbol_group',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='geographic_restrictions_enabled',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='inactivity_fee_after_days',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='inactivity_fee_amount',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='inactivity_fee_enabled',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='kyc_level',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='live_group',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='live_leverage',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='live_platform_slug',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='live_server_name',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='live_symbol_group',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='maintenance_fee_amount',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='maintenance_fee_enabled',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='max_demo_accounts',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='max_live_accounts',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='max_single_deposit',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='max_total_balance',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='min_first_deposit',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='mt5_demo_series',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='mt5_live_series',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='require_email_verified',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='require_id_document',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='require_phone_verified',
        ),
        migrations.RemoveField(
            model_name='tradingaccounttype',
            name='settings_json',
        ),
        migrations.RemoveField(
            model_name='tradingplatformintegration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tradingplatformintegration',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='tradingplatformintegration',
            name='download_android_url',
        ),
        migrations.RemoveField(
            model_name='tradingplatformintegration',
            name='download_ios_url',
        ),
        migrations.RemoveField(
            model_name='tradingplatformintegration',
            name='download_macos_url',
        ),
        migrations.RemoveField(
            model_name='tradingplatformintegration',
            name='download_windows_url',
        ),
        migrations.RemoveField(
            model_name='tradingplatformintegration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tradingplatformintegration',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tradingplatformintegration',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tradingplatformintegration',
            name='web_terminal_url',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='event_key',
            field=models.CharField(choices=[('account_created', 'Account Created'), ('email_verification', 'Email Verification'), ('email_verified', 'Email Verified'), ('forgot_password', 'Forgot Password'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('kyc_submitted', 'KYC Submitted'), ('identity_approved', 'Identity Approved'), ('identity_rejected', 'Identity Rejected'), ('address_approved', 'Address Approved'), ('address_rejected', 'Address Rejected'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('withdrawal_submitted', 'Withdrawal Submitted'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('deposit_submitted', 'Deposit Submitted'), ('ib_request_approved', 'IB Request Approved'), ('ib_request_rejected', 'IB Request Rejected'), ('signup_welcome', 'Signup Welcome'), ('password_reset', 'Password Reset'), ('account_approved', 'Account Approved'), ('real_account_created', 'Real Account Created'), ('demo_account_created', 'Demo Account Created')], max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='legalagreementssettings',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='legal/'),
        ),
        migrations.AlterField(
            model_name='legalagreementssettings',
            name='name',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='organizationprofilesettings',
            name='application_timezone',
            field=models.CharField(blank=True, default='UTC', max_length=64),
        ),
        migrations.AlterField(
            model_name='organizationprofilesettings',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='organizationprofilesettings',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='organizationprofilesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/'),
        ),
        migrations.AlterField(
            model_name='organizationprofilesettings',
            name='organization_id',
            field=models.CharField(default=admin_panel.models._org_public_id, editable=False, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='tradingplatformintegration',
            name='api_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='tradingplatformintegration',
            name='broker_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tradingplatformintegration',
            name='platform',
            field=models.CharField(choices=[('MT4', 'MetaTrader 4'), ('MT5', 'MetaTrader 5'), ('CTRADER', 'cTrader'), ('MATCH_TRADER', 'Match Trader'), ('TRADELOCKER', 'TradeLocker'), ('VERTEX_TRADER', 'Vertex Trader'), ('X9_TRADER', 'X9 Trader')], db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tradingplatformsettings',
            name='platform_name',
            field=models.CharField(blank=True, default='MetaTrader 5', max_length=140),
        ),
        migrations.AlterModelTable(
            name='tradingplatformintegration',
            table=None,
        ),
    ]
