# Generated by Django 6.0.3 on 2026-04-01 06:04

from django.db import migrations, models


def seed_default_white_label(apps, schema_editor):
    WhiteLabelProfile = apps.get_model("admin_panel", "WhiteLabelProfile")
    if WhiteLabelProfile.objects.exists():
        return
    WhiteLabelProfile.objects.create(
        name="Default",
        slug="default",
        is_active_for_portal=True,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_tradingaccounttype_group_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteLabelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=120)),
                ('slug', models.SlugField(blank=True, default='', max_length=64, unique=True)),
                ('is_active_for_portal', models.BooleanField(db_index=True, default=False)),
                ('primary_color', models.CharField(blank=True, default='', max_length=32)),
                ('secondary_color', models.CharField(blank=True, default='', max_length=32)),
                ('sidebar_bg_color', models.CharField(blank=True, default='', max_length=32)),
                ('header_bg_color', models.CharField(blank=True, default='', max_length=32)),
                ('button_color', models.CharField(blank=True, default='', max_length=32)),
                ('content_text_color', models.CharField(blank=True, default='', max_length=32)),
                ('font_size_preset', models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', max_length=8)),
                ('font_weight_preset', models.CharField(choices=[('normal', 'Normal'), ('medium', 'Medium'), ('bold', 'Bold')], default='medium', max_length=16)),
                ('sidebar_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=8)),
                ('sidebar_width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('header_height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('menu_icon_size_px', models.PositiveIntegerField(blank=True, null=True)),
                ('border_radius_px', models.PositiveIntegerField(blank=True, null=True)),
                ('company_name_override', models.CharField(blank=True, default='', max_length=160)),
                ('footer_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='portalbrandingsettings',
            name='user_dashboard_logo_dark',
            field=models.FileField(blank=True, help_text='Optional dark-theme variant for client portal sidebar/header.', null=True, upload_to='branding'),
        ),
        migrations.AlterField(
            model_name='sidebaruisettings',
            name='font_size',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.RunPython(seed_default_white_label, noop_reverse),
    ]
