# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


def forward_copy_legacy_legal(apps, schema_editor):
    LegalAgreementSettings = apps.get_model("admin_panel", "LegalAgreementSettings")
    LegalDocument = apps.get_model("admin_panel", "LegalDocument")
    LegacySettings = apps.get_model("admin_panel", "LegalAgreementsSettings")
    LegacyCustom = apps.get_model("admin_panel", "LegalCustomDocument")

    legacy = LegacySettings.objects.order_by("id").first()
    if not legacy:
        return

    settings_obj, _created = LegalAgreementSettings.objects.get_or_create(
        pk=1,
        defaults={
            "name": (legacy.name or "Legal Agreements"),
            "tagline": legacy.tagline or "",
            "icon": legacy.icon,
        },
    )
    if not _created:
        settings_obj.name = (legacy.name or settings_obj.name or "Legal Agreements")
        settings_obj.tagline = legacy.tagline or settings_obj.tagline
        if legacy.icon:
            settings_obj.icon = legacy.icon
        settings_obj.save()

    rows = [
        ("ESSENTIAL", "Terms & Conditions", legacy.terms_conditions_url, 10),
        ("ESSENTIAL", "Privacy Policy", legacy.privacy_policy_url, 20),
        ("ESSENTIAL", "Client Agreement", legacy.client_agreement_url, 30),
        ("ESSENTIAL", "Risk Disclosure", legacy.risk_disclosure_url, 40),
        ("ESSENTIAL", "AML Policy", legacy.aml_policy_url, 50),
        ("ESSENTIAL", "Cookie Policy", legacy.cookie_policy_url, 60),
        ("ESSENTIAL", "Disclaimer", legacy.disclaimer_url, 70),
        ("TRADING", "Bonus Policy", legacy.bonus_credit_policy_url, 10),
        ("TRADING", "Withdrawal Policy", legacy.withdrawal_policy_url, 20),
        ("TRADING", "Deposit Policy", legacy.deposit_policy_url, 30),
        ("REGIONAL", "US Client Policy", legacy.us_client_policy_url, 10),
        ("REGIONAL", "EU/UK Policy", legacy.eu_uk_client_policy_url, 20),
        ("ADDITIONAL", "Complaints Policy", legacy.complaints_policy_url, 10),
        ("ADDITIONAL", "Conflict of Interest", legacy.conflict_interest_policy_url, 20),
    ]
    for category, title, link, order in rows:
        clean_link = (link or "").strip()
        LegalDocument.objects.update_or_create(
            category=category,
            title=title,
            defaults={
                "link": clean_link or "https://example.com",
                "order": order,
                "is_active": bool(clean_link),
            },
        )

    custom_rows = LegacyCustom.objects.filter(is_active=True).order_by("sort_order", "id")
    for row in custom_rows:
        if not (row.name or "").strip() or not (row.url or "").strip():
            continue
        LegalDocument.objects.update_or_create(
            category="CUSTOM",
            title=(row.name or "").strip(),
            defaults={
                "link": (row.url or "").strip(),
                "order": row.sort_order or 0,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0033_white_label_profile_and_portal_assets"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalAgreementSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="legal/")),
                ("name", models.CharField(blank=True, default="Legal Agreements", max_length=140)),
                ("tagline", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ESSENTIAL", "Essential Documents"),
                            ("TRADING", "Trading Policies"),
                            ("REGIONAL", "Regional Policies"),
                            ("ADDITIONAL", "Additional Policies"),
                            ("CUSTOM", "Custom Documents"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("link", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["category", "order", "id"]},
        ),
        migrations.AddConstraint(
            model_name="legaldocument",
            constraint=models.UniqueConstraint(fields=("category", "title"), name="uniq_legal_document_category_title"),
        ),
        migrations.RunPython(forward_copy_legacy_legal, migrations.RunPython.noop),
    ]

