# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0037_account_type_wizard_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=False)),
                ("secret_bypass_key", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(blank=True, default="System Under Maintenance", max_length=160)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="We are currently performing scheduled maintenance. Please check back shortly.",
                    ),
                ),
                ("estimated_time", models.CharField(blank=True, default="", max_length=120)),
                ("support_email", models.EmailField(blank=True, default="", max_length=254)),
                ("allow_whitelist_ip", models.BooleanField(default=False)),
                (
                    "whitelist_ips",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated IPs that can bypass maintenance mode.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

