# Generated by Django 6.0.3 on 2026-04-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0038_maintenancesettings'),
        ('admin_panel', '0039_merge_0038_datacenter_and_platform'),
    ]

    operations = [
    ]
