# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0040_merge_20260401_0137"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivitySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "active_period_preset",
                    models.CharField(
                        choices=[("7", "7 Days"), ("15", "15 Days"), ("30", "30 Days"), ("CUSTOM", "Custom")],
                        default="30",
                        max_length=10,
                    ),
                ),
                ("custom_active_days", models.PositiveIntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

