# Generated by Django 6.0.3 on 2026-04-01 15:40

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0047_email_global_layout_template_type_rename_table'),
        ('transactions', '0007_paymentgateway_deposit_type_and_filters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['category', 'name', 'event_key']},
        ),
        migrations.AlterField(
            model_name='adminauthbrandingsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='D:\\forex_crm\\static\\uploads\\logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='D:\\forex_crm\\static\\uploads\\logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(help_text='Use variables: {{name}}, {{email}}, {{amount}}, {{reason}}, {{company_name}}, {{date}}, {{account_number}}, {{verify_url}}, {{upload_url}}'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='sidebaruisettings',
            name='sidebar_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='D:\\forex_crm\\static\\uploads\\logo'), upload_to='sidebar'),
        ),
        migrations.AlterField(
            model_name='userauthbrandingsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='D:\\forex_crm\\static\\uploads\\logo'), upload_to=''),
        ),
        migrations.CreateModel(
            name='BonusTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('bonus_type', models.CharField(choices=[('DEPOSIT', 'Deposit bonus'), ('NO_DEPOSIT', 'No deposit bonus'), ('TRADING', 'Trading bonus')], default='DEPOSIT', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('template_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused')], db_index=True, default='ACTIVE', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher runs first when multiple match.')),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('amount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED', 'Fixed amount')], default='PERCENT', max_length=12)),
                ('amount_value', models.DecimalField(decimal_places=4, default=0, help_text='Percent or fixed amount.', max_digits=18)),
                ('max_bonus_amount', models.DecimalField(decimal_places=2, default=0, help_text='Cap per grant; 0 = no cap.', max_digits=18)),
                ('min_deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum deposit to qualify; 0 = none.', max_digits=18)),
                ('max_grants_per_user', models.PositiveIntegerField(default=0, help_text='0 = unlimited applications per user.')),
                ('withdrawal_rule', models.CharField(choices=[('REMOVE_FULL', 'Remove full bonus on withdrawal'), ('REMOVE_PARTIAL', 'Remove partial bonus'), ('KEEP_BONUS', 'Keep bonus')], default='KEEP_BONUS', max_length=20)),
                ('expiry_days', models.PositiveIntegerField(default=0, help_text='Days until granted bonus expires; 0 = not enforced by CRM.')),
                ('country_filter_type', models.CharField(choices=[('NONE', 'No country filter'), ('ALLOW', 'Allowed countries only'), ('BLOCK', 'Blocked countries')], default='NONE', max_length=12)),
                ('allowed_countries', models.TextField(blank=True, default='', help_text='Comma-separated ISO codes or country names.')),
                ('blocked_countries', models.TextField(blank=True, default='')),
                ('min_kyc_level', models.CharField(choices=[('NONE', 'None'), ('BASIC', 'Basic (ID in progress or verified)'), ('FULL', 'Fully approved')], default='NONE', max_length=12)),
                ('filter_require_vip', models.BooleanField(default=False, help_text='User must have a tag whose name contains “VIP”.')),
                ('filter_require_high_value', models.BooleanField(default=False, help_text='Wallet balance must meet threshold.')),
                ('filter_require_problem_user', models.BooleanField(default=False, help_text='User must have a tag matching “problem”.')),
                ('filter_require_watch_list', models.BooleanField(default=False, help_text='User must have a tag matching “watch”.')),
                ('high_value_min_balance', models.DecimalField(decimal_places=2, default=10000, help_text='Used when High value filter is on.', max_digits=20)),
                ('risk_tags_raw', models.TextField(blank=True, default='', help_text='One rule per line; user must have a tag whose name contains the line text (case-insensitive).')),
                ('auto_apply_trigger', models.CharField(choices=[('SIGNUP', 'On signup'), ('TRADING_ACCOUNT_OPENED', 'On live trading account created'), ('FIRST_DEPOSIT', 'On first deposit'), ('EVERY_DEPOSIT', 'On every deposit'), ('KYC_APPROVED', 'On KYC approved'), ('MANUAL_ONLY', 'Manual admin apply only')], db_index=True, default='MANUAL_ONLY', max_length=32)),
                ('bonus_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('MULTI', 'Multi (follow account / transaction)')], default='USD', max_length=12)),
                ('bonus_basis', models.CharField(choices=[('DEPOSIT_AMOUNT', 'Based on deposit amount'), ('FIXED', 'Fixed bonus'), ('TIER', 'Tier based on deposit')], default='DEPOSIT_AMOUNT', max_length=20)),
                ('max_bonus_total', models.DecimalField(decimal_places=2, default=0, help_text='Global cap across all users; 0 = unlimited.', max_digits=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_types', models.ManyToManyField(blank=True, help_text='Empty = all account types.', related_name='bonus_templates', to='admin_panel.tradingaccounttype')),
            ],
            options={
                'ordering': ['-priority', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BonusTemplateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_template_applications', to='transactions.transaction')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admin_panel.bonustemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_template_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BonusTemplateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('deposit_min', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deposit_max', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('bonus_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bonus_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='admin_panel.bonustemplate')),
            ],
            options={
                'ordering': ['sort_order', 'deposit_min', 'id'],
            },
        ),
    ]
