# Generated by Django 6.0.3 on 2026-04-01 17:50

import admin_panel.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0049_email_template_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplatesettings',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text='Company name text on the email header bar.', max_length=7),
        ),
        migrations.AlterField(
            model_name='emailtemplatesettings',
            name='email_logo',
            field=models.FileField(blank=True, help_text='PNG, JPG, or SVG. Used in email headers when set.', max_length=500, null=True, upload_to='email_template_settings/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg']), admin_panel.models._validate_email_logo_file_size]),
        ),
        migrations.AlterField(
            model_name='emailtemplatesettings',
            name='header_color',
            field=models.CharField(default='#0B1C3F', max_length=7),
        ),
    ]
