# Generated by Django 6.0.3 on 2026-04-03 10:00

from decimal import Decimal

from django.db import migrations, models


def forwards_fill_active_days_from_preset(apps, schema_editor):
    UserActivitySettings = apps.get_model("admin_panel", "UserActivitySettings")
    for row in UserActivitySettings.objects.all():
        preset = row.active_period_preset
        if preset == "CUSTOM":
            row.active_days = max(int(row.custom_active_days or 15), 1)
        else:
            try:
                row.active_days = max(int(preset), 1)
            except (TypeError, ValueError):
                row.active_days = 15
        row.save(update_fields=["active_days"])


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0052_seed_default_trading_account_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivitysettings",
            name="active_days",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Users count as active if they logged in within this many days (and meet balance rules).",
            ),
        ),
        migrations.AddField(
            model_name="useractivitysettings",
            name="min_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Minimum live MT5 account balance (USD) for active-user rules.",
                max_digits=10,
            ),
        ),
        migrations.RunPython(forwards_fill_active_days_from_preset, migrations.RunPython.noop),
    ]
