# Generated by Django 6.0.3 on 2026-04-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0053_useractivitysettings_active_days_min_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTraderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('grpc_address', models.CharField(blank=True, default='', help_text='gRPC endpoint (e.g. host:port).', max_length=500)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('connection_status', models.CharField(choices=[('Disconnected', 'Disconnected'), ('Connected', 'Connected'), ('Error', 'Error')], default='Disconnected', max_length=32)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('sync_users', models.BooleanField(default=False)),
                ('sync_accounts', models.BooleanField(default=False)),
                ('sync_trades', models.BooleanField(default=False)),
                ('sync_balance', models.BooleanField(default=False)),
                ('sync_deposits', models.BooleanField(default=False)),
                ('sync_withdrawals', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match-Trader integration',
                'verbose_name_plural': 'Match-Trader integration',
            },
        ),
    ]
