# Generated by Django 6.0.3 on 2026-04-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0054_match_trader_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTraderBrokerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exact group name on Match-Trader (e.g. standard).', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match-Trader broker group',
                'verbose_name_plural': 'Match-Trader broker groups',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='match_trader_group',
            field=models.ForeignKey(blank=True, help_text='Match-Trader group mapped to this CRM account type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_types', to='admin_panel.matchtraderbrokergroup'),
        ),
    ]
