# Generated by Django 6.0.3 on 2026-04-06 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_crm_group_symbol_sync'),
        ('admin_panel', '0060_tradingaccounttype_remove_match_trader_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchtradersettings',
            options={'verbose_name': 'Match-Trader configuration', 'verbose_name_plural': 'Match-Trader configuration'},
        ),
        migrations.AlterField(
            model_name='matchtradersettings',
            name='last_test_success_at',
            field=models.DateTimeField(blank=True, help_text='Last successful gRPC TLS handshake to the broker gRPC endpoint.', null=True),
        ),
        migrations.AlterField(
            model_name='tradingaccounttype',
            name='crm_group',
            field=models.ForeignKey(blank=True, help_text='CRM group from Group Management (maps to MT5 / Match-Trader at group level).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_types', to='accounts.mt5group'),
        ),
        migrations.CreateModel(
            name='CrmGroupSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('symbol_count', models.PositiveIntegerField(default=0)),
                ('mt5_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_symbol_sync_status', to='accounts.mt5group')),
            ],
        ),
        migrations.CreateModel(
            name='CrmGroupSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(db_index=True, max_length=64)),
                ('source_platform', models.CharField(choices=[('MATCH_TRADER', 'Match-Trader'), ('MT5', 'MT5'), ('X9', 'X9'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('mt5_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_synced_symbols', to='accounts.mt5group')),
            ],
            options={
                'ordering': ['mt5_group_id', 'symbol_name'],
                'constraints': [models.UniqueConstraint(fields=('mt5_group', 'symbol_name'), name='uniq_crmgroupsymbol_group_name')],
            },
        ),
    ]
