# Generated by Django 6.0.3 on 2026-04-07 02:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_crm_departments(apps, schema_editor):
    CrmDepartment = apps.get_model("admin_panel", "CrmDepartment")
    for slug, name in (
        ("sales-manager", "Sales Manager"),
        ("kyc", "KYC Department"),
        ("finance", "Finance Department"),
        ("support", "Support Department"),
    ):
        CrmDepartment.objects.get_or_create(
            slug=slug, defaults={"name": name, "is_active": True, "description": ""}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0062_matchtradersettings_rest_base_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrmStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_slug', models.SlugField(help_text='URL segment for manager referral links (e.g. john-smith).', max_length=80, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM staff profile',
                'verbose_name_plural': 'CRM staff profiles',
            },
        ),
        migrations.CreateModel(
            name='CrmPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(db_index=True, max_length=64)),
                ('granted', models.BooleanField(default=True, help_text='False explicitly denies even if department allows.')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_permission_grants', to='admin_panel.crmdepartment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_permission_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('department__isnull', False), _connector='OR'), name='crm_perm_grant_has_target'), models.CheckConstraint(condition=models.Q(('user__isnull', False), ('department__isnull', False), _negated=True), name='crm_perm_grant_single_target'), models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('user', 'permission_code'), name='crm_perm_grant_unique_user_code'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('department', 'permission_code'), name='crm_perm_grant_unique_dept_code')],
            },
        ),
        migrations.RunPython(seed_crm_departments, migrations.RunPython.noop),
    ]
