# Generated by Django 6.0.3 on 2026-04-07 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0063_crm_sales_rbac'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False, help_text='Built-in roles seeded by migrations; can still edit grants.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrmRoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(db_index=True, max_length=64)),
                ('granted', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='admin_panel.crmrole')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'permission_code'), name='crm_role_grant_unique_role_code')],
            },
        ),
    ]
