# Generated by Django 6.0.3 on 2026-04-07 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_manager_clients_from_user_fk(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    ManagerClient = apps.get_model("admin_panel", "ManagerClient")
    for u in User.objects.filter(
        role="CLIENT", registered_via_sales_manager_id__isnull=False
    ).only("id", "registered_via_sales_manager_id"):
        ManagerClient.objects.get_or_create(
            manager_id=u.registered_via_sales_manager_id,
            client_id=u.id,
            defaults={"assigned_by_id": None},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0064_crm_roles_and_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0028_crm_sales_rbac'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_clients_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_client_assignments', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'SALES_MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_manager_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manager client assignment',
                'verbose_name_plural': 'manager client assignments',
                'constraints': [models.UniqueConstraint(fields=('manager', 'client'), name='uniq_manager_client_pair')],
            },
        ),
        migrations.RunPython(backfill_manager_clients_from_user_fk, noop_reverse),
    ]
