# Generated by Django 6.0.3 on 2026-04-07 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0065_manager_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('deposit', 'Deposit based'), ('volume', 'Volume based')], max_length=16)),
                ('target_value', models.DecimalField(decimal_places=4, help_text='Deposit: currency amount (e.g. USD). Volume: sum of lots.', max_digits=20)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='monthly', max_length=16)),
                ('start_date', models.DateField(blank=True, help_text='Optional fixed window start; if set with end_date, overrides period.', null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'SALES_MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_targets',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('manager',), name='uniq_active_manager_target_per_manager')],
            },
        ),
    ]
