# Generated by Django 6.0.3 on 2026-04-07 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0066_manager_targets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='managertarget',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role__in': ['SALES_MANAGER', 'MANAGER']}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ManagerPortalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_clients', models.BooleanField(default=False)),
                ('view_deposit', models.BooleanField(default=False)),
                ('view_withdrawal', models.BooleanField(default=False)),
                ('view_volume', models.BooleanField(default=False)),
                ('view_balance', models.BooleanField(default=False)),
                ('view_trades', models.BooleanField(default=False)),
                ('view_personal_info', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.OneToOneField(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_portal_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_permissions',
            },
        ),
        migrations.CreateModel(
            name='ManagerAssignedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_portal_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role__in': ['CLIENT', 'TRADER', 'COPIER']}, on_delete=django.db.models.deletion.CASCADE, related_name='account_manager_assignments', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_portal_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_assigned_clients',
                'constraints': [models.UniqueConstraint(fields=('manager', 'client'), name='uniq_manager_portal_manager_client')],
            },
        ),
    ]
