# Generated by Django 6.0.3 on 2026-04-08 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0067_manager_portal_permissions_and_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StabilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('development', 'Development'), ('stable', 'Stable')], default='development', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stability_profiles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stability_profiles',
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('stability', models.CharField(choices=[('development', 'Development'), ('stable', 'Stable')], default='development', max_length=16)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_system_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_modules',
                'ordering': ['module_name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(blank=True, default='', max_length=60)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('changed_paths', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_change_logs', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='admin_panel.systemmodule')),
            ],
            options={
                'db_table': 'module_change_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_version', models.CharField(db_index=True, max_length=40)),
                ('backup_path', models.CharField(blank=True, default='', max_length=500)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_module_versions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='admin_panel.systemmodule')),
            ],
            options={
                'db_table': 'module_versions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('module', 'module_version'), name='uniq_module_version_per_module')],
            },
        ),
    ]
