# Generated by Django 6.0.3 on 2026-04-08 08:55

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def seed_purposes_and_mappings(apps, schema_editor):
    EmailTemplate = apps.get_model("admin_panel", "EmailTemplate")
    EmailPurpose = apps.get_model("admin_panel", "EmailPurpose")
    EmailTemplateMapping = apps.get_model("admin_panel", "EmailTemplateMapping")

    for tpl in EmailTemplate.objects.all().only("id", "name", "event_key"):
        base = (tpl.event_key or tpl.name or "").strip()
        if not base:
            continue
        purpose_key = slugify(base)[:80]
        if not purpose_key:
            continue
        purpose_name = (base.replace("_", " ").replace("-", " ").title() or "Purpose")[:120]
        purpose, _ = EmailPurpose.objects.get_or_create(
            purpose_key=purpose_key,
            defaults={"purpose_name": purpose_name},
        )
        if getattr(tpl, "purpose_id", None) != purpose.id:
            tpl.purpose_id = purpose.id
            tpl.save(update_fields=["purpose"])
        EmailTemplateMapping.objects.update_or_create(
            purpose_id=purpose.id,
            defaults={"template_id": tpl.id},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0068_stabilityprofile_systemmodule_modulechangelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_name', models.CharField(max_length=120, unique=True)),
                ('purpose_key', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_purposes',
                'ordering': ['purpose_name'],
            },
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='admin_panel.emailpurpose'),
        ),
        migrations.CreateModel(
            name='EmailTemplateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_mapping', to='admin_panel.emailpurpose')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_mappings', to='admin_panel.emailtemplate')),
            ],
            options={
                'db_table': 'email_template_mapping',
                'ordering': ['purpose__purpose_name'],
            },
        ),
        migrations.RunPython(seed_purposes_and_mappings, noop_reverse),
    ]
