# Generated by Django 6.0.3 on 2026-04-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0069_email_purpose_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10),
        ),
    ]
