# Generated by Django 6.0.3 on 2026-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0070_emailtemplate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplatesettings',
            name='button_color',
            field=models.CharField(default='#0B3C5D', help_text='Primary button color used in wrapped email templates.', max_length=7),
        ),
        migrations.AddField(
            model_name='emailtemplatesettings',
            name='company_name_override',
            field=models.CharField(blank=True, default='', help_text='Optional company name override for all outgoing transactional emails.', max_length=180),
        ),
    ]
