# Generated by Django 6.0.5 on 2026-05-19 15:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0072_match2payintegrationsettings_documentation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauthbrandingsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='C:\\Users\\ayush\\OneDrive\\Documents\\GitHub\\Burjex-Prime-Crm\\static\\uploads\\logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='C:\\Users\\ayush\\OneDrive\\Documents\\GitHub\\Burjex-Prime-Crm\\static\\uploads\\logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sidebaruisettings',
            name='sidebar_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='C:\\Users\\ayush\\OneDrive\\Documents\\GitHub\\Burjex-Prime-Crm\\static\\uploads\\logo'), upload_to='sidebar'),
        ),
        migrations.AlterField(
            model_name='userauthbrandingsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='C:\\Users\\ayush\\OneDrive\\Documents\\GitHub\\Burjex-Prime-Crm\\static\\uploads\\logo'), upload_to=''),
        ),
    ]
