# Generated by Django 5.2.14 on 2026-05-22 05:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0073_alter_adminauthbrandingsettings_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportintegration',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='supportintegration',
            name='chat_bubble_icon',
        ),
        migrations.RemoveField(
            model_name='supportintegration',
            name='chat_widget',
        ),
        migrations.RemoveField(
            model_name='supportintegration',
            name='support_email',
        ),
        migrations.RemoveField(
            model_name='supportintegration',
            name='token',
        ),
        migrations.AlterField(
            model_name='adminauthbrandingsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='/root/crm/Burjex-Prime-Crm/static/uploads/logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='/root/crm/Burjex-Prime-Crm/static/uploads/logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sidebaruisettings',
            name='sidebar_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='/root/crm/Burjex-Prime-Crm/static/uploads/logo'), upload_to='sidebar'),
        ),
        migrations.AlterField(
            model_name='supportintegration',
            name='integration_type',
            field=models.CharField(choices=[('WHATSAPP_DIRECT', 'WhatsApp Direct'), ('TAWK_TO', 'Tawk.to'), ('ZOHO_SALESIQ', 'Zoho SalesIQ')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userauthbrandingsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='/root/crm/Burjex-Prime-Crm/static/uploads/logo'), upload_to=''),
        ),
    ]
