# Generated by Codex on 2026-06-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0075_alter_adminauthbrandingsettings_logo_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WhitelistTreasurySettings",
        ),
    ]
