# Generated by Codex on 2026-06-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_remove_bonus_template"),
        ("admin_panel", "0076_remove_whitelist_treasury_settings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BonusTemplateApplication",
        ),
        migrations.DeleteModel(
            name="BonusTemplateTier",
        ),
        migrations.DeleteModel(
            name="BonusTemplate",
        ),
    ]
