# Generated by Codex on 2026-06-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0077_remove_rewards_management"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataCenterMcpSettings",
        ),
        migrations.DeleteModel(
            name="DataCenterImportJob",
        ),
        migrations.DeleteModel(
            name="DataCenterEventLog",
        ),
        migrations.DeleteModel(
            name="DataCenterBackup",
        ),
        migrations.DeleteModel(
            name="DataCenterApiKey",
        ),
        migrations.DeleteModel(
            name="DataCenterWebhook",
        ),
    ]
