# Generated by Django 6.0.5 on 2026-06-20 14:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0082_alter_adminauthbrandingsettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccounttype',
            name='suitable_for',
            field=models.CharField(blank=True, default='All Traders', max_length=120),
        ),
        migrations.AlterField(
            model_name='adminauthbrandingsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='C:\\Users\\ayush\\OneDrive\\Documents\\GitHub\\Burjex-Prime-Crm\\static\\uploads\\logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='C:\\Users\\ayush\\OneDrive\\Documents\\GitHub\\Burjex-Prime-Crm\\static\\uploads\\logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sidebaruisettings',
            name='sidebar_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='C:\\Users\\ayush\\OneDrive\\Documents\\GitHub\\Burjex-Prime-Crm\\static\\uploads\\logo'), upload_to='sidebar'),
        ),
        migrations.AlterField(
            model_name='userauthbrandingsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='C:\\Users\\ayush\\OneDrive\\Documents\\GitHub\\Burjex-Prime-Crm\\static\\uploads\\logo'), upload_to=''),
        ),
    ]
