# Generated by Django 5.2.14 on 2026-06-20 17:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0083_tradingaccounttype_suitable_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauthbrandingsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='/root/crm/Burjex-Prime-Crm/static/uploads/logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='/root/crm/Burjex-Prime-Crm/static/uploads/logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sidebaruisettings',
            name='sidebar_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='/root/crm/Burjex-Prime-Crm/static/uploads/logo'), upload_to='sidebar'),
        ),
        migrations.AlterField(
            model_name='userauthbrandingsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/uploads/logo/', location='/root/crm/Burjex-Prime-Crm/static/uploads/logo'), upload_to=''),
        ),
    ]
