# Generated by Django 6.0.5 on 2026-06-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0085_legaldocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingplatform',
            name='android_file',
            field=models.FileField(blank=True, null=True, upload_to='platforms/downloads/'),
        ),
        migrations.AddField(
            model_name='tradingplatform',
            name='ios_file',
            field=models.FileField(blank=True, null=True, upload_to='platforms/downloads/'),
        ),
        migrations.AddField(
            model_name='tradingplatform',
            name='mac_file',
            field=models.FileField(blank=True, null=True, upload_to='platforms/downloads/'),
        ),
        migrations.AddField(
            model_name='tradingplatform',
            name='windows_file',
            field=models.FileField(blank=True, null=True, upload_to='platforms/downloads/'),
        ),
    ]
