# Generated by Django 5.2.14 on 2026-07-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0087_alter_adminauthbrandingsettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmonitorsettings',
            name='enable_country_mismatch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riskmonitorsettings',
            name='hedging_time_window_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='riskmonitorsettings',
            name='hft_trades_per_minute',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='riskmonitorsettings',
            name='high_profit_threshold',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='riskmonitorsettings',
            name='large_lot_threshold',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riskmonitorsettings',
            name='multiple_ip_monitoring_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='riskmonitorsettings',
            name='short_duration_max_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='riskmonitorsettings',
            name='single_symbol_monitoring_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
