# Generated by Django 5.2.13 on 2026-07-27 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_mt5account_group'),
        ('admin_panel', '0088_riskmonitorsettings_enable_country_mismatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccounttype',
            name='account_category',
            field=models.CharField(choices=[('LIVE', 'Live'), ('DEMO', 'Demo')], default='LIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='max_demo_balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, help_text='Maximum initial balance for Demo Accounts', max_digits=12),
        ),
        migrations.AddField(
            model_name='tradingaccounttype',
            name='min_demo_balance',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum initial balance for Demo Accounts', max_digits=12),
        ),
        migrations.AlterField(
            model_name='tradingaccounttype',
            name='demo_group',
            field=models.ForeignKey(blank=True, help_text='If this is a Live account with demo enabled, specify the group for demo accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_account_types', to='accounts.mt5group'),
        ),
    ]
