"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

try:
    import django_celery_results  # noqa: F401

    _DJANGO_CELERY_RESULTS = True
except ImportError:
    _DJANGO_CELERY_RESULTS = False


def _env_csv(name: str) -> list[str]:
    return [x.strip() for x in (os.environ.get(name) or "").split(",") if x.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: set DJANGO_SECRET_KEY in production; dev fallback only.
SECRET_KEY = (os.environ.get("DJANGO_SECRET_KEY") or "").strip() or (
    "django-insecure-4q-0$7)0!dfmeb#f_pr-#)w377m(=mc%0#&gsmubnii6@zbb!a"
)

# SECURITY WARNING: set DJANGO_DEBUG=0 in production.
DEBUG = _env_bool("DJANGO_DEBUG", True)

_hosts = [x.strip() for x in (os.environ.get("DJANGO_ALLOWED_HOSTS") or "").split(",") if x.strip()]
if _hosts:
    ALLOWED_HOSTS = _hosts
elif DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    # Production: set DJANGO_ALLOWED_HOSTS (comma-separated). Fallback avoids empty ALLOWED_HOSTS.
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://192.168.0.104:8000",
    "http://187.77.150.39",
    "http://187.77.150.39:8000",
    "http://crm.burjexprime.com",
    "https://187.77.150.39",
    "https://crm.burjexprime.com",
]
# Production: add the real origins (scheme required) via env CSV.
for _origin in _env_csv("DJANGO_CSRF_TRUSTED_ORIGINS"):
    if _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)

# Local / LAN dev: allow login forms over HTTP without Secure cookies.
# Behind HTTPS set DJANGO_COOKIE_SECURE=1 so session/CSRF cookies are Secure.
CSRF_COOKIE_SECURE = _env_bool("DJANGO_COOKIE_SECURE", False)
SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE
CSRF_COOKIE_HTTPONLY = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'channels',

    # Third-party
    'solo',
    'django_ckeditor_5',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # Project apps
    'accounts',
    'admin_panel.apps.AdminPanelConfig',
    'user_portal',
    'transactions',
    'ib',
    'marketing',
    'pamm',
    'copier',
    'regulations',
    'enterprise.apps.EnterpriseConfig',
    'live_chat',
    'manager_panel.apps.ManagerPanelConfig',
    'email_notifications.apps.EmailNotificationsConfig',
    'mt5_integration',
    'btrader_integration.apps.BtraderIntegrationConfig',
    'api.apps.ApiConfig',
]
if _DJANGO_CELERY_RESULTS:
    INSTALLED_APPS.append("django_celery_results")

# Enable caching for django-solo settings
SOLO_CACHE = "default"
SOLO_CACHE_TIMEOUT = 60 * 5
SOLO_CACHE_PREFIX = "solo"

# CKEditor 5 configuration for email template editing
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "underline", "strikethrough", "|",
            "link", "bulletedList", "numberedList", "|",
            "blockQuote", "insertTable", "|",
            "undo", "redo",
        ],
    },
    "extends": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "underline", "strikethrough",
            "fontColor", "fontBackgroundColor", "|",
            "link", "bulletedList", "numberedList", "|",
            "alignment", "|",
            "blockQuote", "insertTable", "horizontalLine", "|",
            "sourceEditing", "|",
            "undo", "redo",
        ],
        "heading": {
            "options": [
                {"model": "paragraph", "title": "Body", "class": "ck-heading_paragraph"},
                {"model": "heading1", "view": "h1", "title": "Heading 1"},
                {"model": "heading2", "view": "h2", "title": "Heading 2"},
                {"model": "heading3", "view": "h3", "title": "Heading 3"},
            ],
        },
        "htmlSupport": {
            "allow": [
                {"name": ".*", "attributes": True, "classes": True, "styles": True},
            ],
        },
    },
}
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.default_storage"


MIDDLEWARE = [
    'admin_panel.middleware.ModuleProtectionMiddleware',
    'user_portal.middleware.PortalTemplateFallbackMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'enterprise.middleware.FailedLoginLockoutMiddleware',
    'config.middleware.Custom404Middleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'admin_panel.middleware.MaintenanceModeMiddleware',
    'enterprise.middleware.AdminIPAllowlistMiddleware',
    'accounts.middleware.AdminMiddleware',
    'accounts.middleware.UserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'enterprise.middleware.ExtraSecurityHeadersMiddleware',
]

# --- REST API (Flutter / mobile / SPA clients) ---
# HTML Admin & Client portals remain unchanged; JSON APIs live under /api/v1/.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "EXCEPTION_HANDLER": "api.exceptions.crm_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "NON_FIELD_ERRORS_KEY": "non_field_errors",
}

# CORS for Flutter / web API clients (override with CORS_ALLOWED_ORIGINS env CSV in production).
CORS_ALLOW_CREDENTIALS = True
_cors = _env_csv("CORS_ALLOWED_ORIGINS")
if _cors:
    CORS_ALLOWED_ORIGINS = _cors
elif DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = list(CSRF_TRUSTED_ORIGINS)

CRM_STABILITY_MODE = (os.environ.get("CRM_STABILITY_MODE") or "development").strip().lower()
if CRM_STABILITY_MODE not in ("development", "stable"):
    CRM_STABILITY_MODE = "development"

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            # Use cached loader in production for a significant speed boost.
            # In DEBUG mode, templates reload from disk on every request (development convenience).
            'debug': DEBUG,
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ] if not DEBUG else [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.portal_client_meta',
                'admin_panel.context_processors.crm_shell_layout_context',
                'sales_panel.context_processors.sales_portal_feature_flags',
                'admin_panel.context_processors.crm_sales_manager_minimal_admin_nav',
                'admin_panel.context_processors.dashboard_settings_context',
                'admin_panel.context_processors.branding_and_sidebar_ui_context',
                'admin_panel.context_processors.branding',
                'admin_panel.context_processors.trading_platforms_public_context',
                'admin_panel.context_processors.organization_public_context',
                'admin_panel.context_processors.portal_company_override_context',
                'admin_panel.context_processors.legal_agreements_public_context',
                'admin_panel.context_processors.trading_platform_public_context',
                'live_chat.context_processors.live_chat_widget_context',
                'admin_panel.context_processors.support_public_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"
# InMemoryChannelLayer only fans out within ONE process, so live_chat messages
# would be invisible to users pinned to a different gunicorn worker. Set
# CHANNELS_REDIS_URL in production to share the layer across all workers.
_channels_redis = (os.environ.get("CHANNELS_REDIS_URL") or "").strip()
if _channels_redis:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [_channels_redis]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Postgres when POSTGRES_DB is set (production/Docker); SQLite otherwise so a
# plain `python manage.py runserver` checkout keeps working with no env setup.
if os.environ.get("POSTGRES_DB"):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ["POSTGRES_DB"],
            'USER': os.environ.get("POSTGRES_USER", "postgres"),
            'PASSWORD': os.environ.get("POSTGRES_PASSWORD", ""),
            'HOST': os.environ.get("POSTGRES_HOST", "127.0.0.1"),
            'PORT': os.environ.get("POSTGRES_PORT", "5432"),
            # Reuse connections across requests; 0 would reconnect every hit.
            'CONN_MAX_AGE': int((os.environ.get("POSTGRES_CONN_MAX_AGE") or "60").strip() or "60"),
            'CONN_HEALTH_CHECKS': True,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Broker server time (UTC+3), so CRM timestamps match the MT5 terminal, the
# price feed and the trader app instead of drifting per viewer. Storage stays
# UTC via USE_TZ — this only controls rendering. "Etc/GMT-3" is UTC+3: the
# POSIX sign is inverted. Override if the broker moves off UTC+3 (e.g. EET
# winter time) without rebuilding the image.
TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Etc/GMT-3')

USE_I18N = True
USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ("en", "English"),
    ("ur", "Urdu"),
    ("ar", "Arabic"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom auth user model
AUTH_USER_MODEL = 'accounts.User'

# Auth redirects
LOGIN_URL = '/user/login/'
LOGIN_REDIRECT_URL = '/user/dashboard/'
LOGOUT_REDIRECT_URL = '/user/login/'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600

# TLS / HSTS: enable when Django terminates HTTPS or set SECURE_PROXY_SSL_HEADER behind a reverse proxy.
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SECURE_PROXY_SSL_HEADER = None
if _env_bool("DJANGO_USE_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = int((os.environ.get("DJANGO_SECURE_HSTS_SECONDS") or "0").strip() or "0")
if SECURE_HSTS_SECONDS > 0:
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", True)
    SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Optional Content-Security-Policy (leave empty if inline scripts/styles break; tune per deployment).
SECURITY_CSP = (os.environ.get("DJANGO_SECURITY_CSP") or "").strip()

# Used for absolute URLs in email layout (logo); set in production (e.g. https://crm.example.com).
SITE_BASE_URL = (os.environ.get("SITE_BASE_URL") or "").strip()

# SMTP (and send_mail): verify TLS with certifi's CA bundle when not using client certs.
# Avoids CERTIFICATE_VERIFY_FAILED on fresh Linux images with an empty system CA store.
# Override: DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "admin_panel.mail_backend.CertifiEmailBackend",
)
# Local/dev: avoid SMTP hangs on login/API when credentials are invalid.
if DEBUG and not os.environ.get("DJANGO_EMAIL_BACKEND"):
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# --- Enterprise: cache, Celery, load-balancer / multi-instance ---
# DEBUG: never touch Redis (LocMem cache + DB sessions + eager Celery).
# Production (DEBUG=False): keep Redis cache / cached_db sessions as before.
if DEBUG:
    REDIS_URL = ""
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "forexcrm-dev",
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.db"
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "django-db" if _DJANGO_CELERY_RESULTS else "cache+memory://"
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
else:
    REDIS_URL = (os.environ.get("REDIS_URL") or "redis://127.0.0.1:6379/0").strip()
    if REDIS_URL:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": REDIS_URL,
            }
        }
        SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
    else:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "forexcrm",
            }
        }
        SESSION_ENGINE = "django.contrib.sessions.backends.db"

    CELERY_BROKER_URL = (os.environ.get("CELERY_BROKER_URL") or REDIS_URL or "redis://127.0.0.1:6379/0").strip()
    CELERY_RESULT_BACKEND = (
        os.environ.get("CELERY_RESULT_BACKEND") or ("django-db" if _DJANGO_CELERY_RESULTS else CELERY_BROKER_URL)
    ).strip()
    _eager = os.environ.get("CELERY_TASK_ALWAYS_EAGER")
    if _eager is None:
        CELERY_TASK_ALWAYS_EAGER = not bool(REDIS_URL)
    else:
        CELERY_TASK_ALWAYS_EAGER = _eager.strip().lower() in ("1", "true", "yes")
    CELERY_TASK_EAGER_PROPAGATES = True

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Optional broker API root when the admin UI does not collect Base URL (env or leave empty for built-in demo default).
MATCH_TRADER_API_BASE = (os.environ.get("MATCH_TRADER_API_BASE") or "").strip()

# Match-Trader enterprise sync (10s tick — accounts, trades, balance, orders, positions).
CELERY_BEAT_SCHEDULE = {
    "matchtrader-enterprise-sync-10s": {
        "task": "admin_panel.tasks.matchtrader_enterprise_sync_task",
        "schedule": 10.0,
    },
    "match2pay-poll-pending-deposits-30s": {
        "task": "transactions.match2pay_poll_pending_deposits",
        "schedule": 30.0,
    },
    "crm-group-symbols-sync-5m": {
        "task": "admin_panel.tasks.crm_group_symbols_sync_beat_task",
        "schedule": 300.0,
    },
    "mt5-account-sync-60s": {
        "task": "mt5_integration.tasks.mt5_account_sync_task",
        "schedule": float(
            (lambda s: int(s.strip()) if s and s.strip().isdigit() else 60)(
                __import__("os").environ.get("MT5_SYNC_INTERVAL_SECONDS", "60")
            )
        ),
    },
    "btrader-account-sync-10s": {
        "task": "btrader_integration.tasks.btrader_account_sync_task",
        "schedule": float(
            (lambda s: int(s.strip()) if s and s.strip().isdigit() else 10)(
                __import__("os").environ.get("BTRADER_SYNC_INTERVAL_SECONDS", "10")
            )
        ),
    },
    "frequent-ib-rebate-sync-5s": {
        "task": "ib.tasks.frequent_ib_rebate_sync_task",
        "schedule": 5.0,
    },
    "daily-ib-rebate-sync": {
        "task": "ib.tasks.daily_ib_rebate_sync_task",
        "schedule": 86400.0,
    },
}
CRM_BACKUP_DIR = (os.environ.get("CRM_BACKUP_DIR") or "").strip() or str(BASE_DIR / "storage" / "backups")
Path(CRM_BACKUP_DIR).mkdir(parents=True, exist_ok=True)

if _env_bool("CRM_BACKUP_BEAT_ENABLED", False):
    _daily_secs = int((os.environ.get("CRM_BACKUP_DAILY_INTERVAL_SECONDS") or "86400").strip() or "86400")
    _weekly_secs = int((os.environ.get("CRM_BACKUP_WEEKLY_INTERVAL_SECONDS") or "604800").strip() or "604800")
    CELERY_BEAT_SCHEDULE = {
        **CELERY_BEAT_SCHEDULE,
        "crm-backup-daily": {
            "task": "enterprise.tasks.crm_backup_task",
            "schedule": float(max(300, _daily_secs)),
        },
        "crm-backup-weekly": {
            "task": "enterprise.tasks.crm_weekly_backup_task",
            "schedule": float(max(3600, _weekly_secs)),
        },
    }

# Comma-separated IPs (use behind LB with X-Forwarded-For as in enterprise.audit.get_client_ip)
ENTERPRISE_ADMIN_IP_ALLOWLIST = _env_csv("ENTERPRISE_ADMIN_IP_ALLOWLIST")
ENTERPRISE_CLIENT_LOGIN_IP_ALLOWLIST = _env_csv("ENTERPRISE_CLIENT_LOGIN_IP_ALLOWLIST")
# Local development: keep allowlist security, but permit loopback + emulator + LAN clients.
ENTERPRISE_CLIENT_LOGIN_ALLOW_PRIVATE_NETWORKS = False
if DEBUG:
    ENTERPRISE_CLIENT_LOGIN_ALLOW_PRIVATE_NETWORKS = True
    for _dev_ip in ("127.0.0.1", "::1", "10.0.2.2", "10.0.2.15"):
        if _dev_ip not in ENTERPRISE_CLIENT_LOGIN_IP_ALLOWLIST:
            ENTERPRISE_CLIENT_LOGIN_IP_ALLOWLIST.append(_dev_ip)

# Microservice / process role label for health JSON and future splits (crm | trading | payment | reporting)
SERVICE_NAME = os.environ.get("SERVICE_NAME", "crm").strip() or "crm"

# ── MT5 Debug Logging ────────────────────────────────────────────────────────
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} | {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "mt5_file": {
            "class": "logging.FileHandler",
            "filename": str(BASE_DIR / "logs" / "mt5_debug.log"),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "mt5_integration": {
            "handlers": ["console", "mt5_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
