# Generated by Django 6.0.3 on 2026-03-25 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PAMMAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pamm_accounts_as_master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PAMMInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAW_REQUESTED', 'Withdraw Requested'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pamm_investments', to=settings.AUTH_USER_MODEL)),
                ('pamm_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='pamm.pammaccount')),
            ],
            options={
                'unique_together': {('pamm_account', 'investor')},
            },
        ),
    ]
