# Generated by Django 6.0.3 on 2026-04-02 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFunnelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_profit_potential_usd', models.DecimalField(decimal_places=2, default=5000, max_digits=14)),
                ('is_dropped', models.BooleanField(default=False)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_reason', models.CharField(blank=True, max_length=500)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_clients_as_agent', to=settings.AUTH_USER_MODEL)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_clients_as_manager', to=settings.AUTH_USER_MODEL)),
                ('last_contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_client_last_contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_funnel_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesFunnelVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('is_dropped', models.BooleanField(default=False)),
                ('profit_potential_usd', models.DecimalField(decimal_places=2, default=2500, max_digits=14)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_visitors_as_agent', to=settings.AUTH_USER_MODEL)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_visitors_as_manager', to=settings.AUTH_USER_MODEL)),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_visitor_captures', to=settings.AUTH_USER_MODEL)),
                ('last_contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_visitor_last_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesFunnelContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('NOTE', 'Note'), ('ASSIGN', 'Assignment')], max_length=20)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_funnel_contact_logs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_funnel_actions_logged', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='marketing.salesfunnelvisitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salesfunnelvisitor',
            index=models.Index(fields=['-created_at'], name='marketing_s_created_8b5311_idx'),
        ),
        migrations.AddIndex(
            model_name='salesfunnelvisitor',
            index=models.Index(fields=['email', 'converted_user'], name='marketing_s_email_724e3e_idx'),
        ),
    ]
