# Generated by Django 6.0.3 on 2026-04-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0063_crm_sales_rbac'),
        ('marketing', '0003_backfill_sales_funnel_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='admin_panel.crmdepartment'),
        ),
    ]
