# Generated by Django 6.0.3 on 2026-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ibcommissionrule',
            name='level_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
