# Generated by Django 6.0.3 on 2026-03-27 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib', '0002_ibcommissionrule_level1_ibcommissionrule_level10_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IBCommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('SPREAD_ONLY', 'Spread Only'), ('COMMISSION_ONLY', 'Commission Only'), ('SPREAD_AND_COMMISSION', 'Spread + Commission')], default='SPREAD_AND_COMMISSION', max_length=30)),
                ('commission_per_lot', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
                ('default_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IBGroupCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=60, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IBLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('target_lots', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('benefits', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IBPairCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ibrequest',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ibrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ibrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ibrequest',
            name='trading_account',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='IBProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ib_type', models.CharField(choices=[('MASTER', 'Master IB'), ('SUB', 'Sub IB')], default='MASTER', max_length=10)),
                ('ib_code', models.CharField(max_length=32, unique=True)),
                ('referral_link', models.CharField(blank=True, max_length=255)),
                ('sub_ib_commission_percent', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('can_view_clients', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_ib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_ib_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ib_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
