# Generated by Django 6.0.3 on 2026-03-29 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib', '0004_ibapplicationquestion_ibrequest_application_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IBUserCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ib_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ib_user_commissions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ib_user_commissions', to='ib.ibplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ib_user', 'plan')},
            },
        ),
    ]
