# Generated by Django 6.0.3 on 2026-03-29 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_kyc_email_symbols_ib_matrix'),
        ('ib', '0005_ibusercommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='iblevel',
            name='target_active_clients',
            field=models.PositiveIntegerField(default=0, help_text='Minimum active referred clients to qualify for this level (0 = ignore).'),
        ),
        migrations.AddField(
            model_name='ibprofile',
            name='ib_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_profiles_at_level', to='ib.iblevel'),
        ),
        migrations.CreateModel(
            name='IBCommissionMatrixRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_mode', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED_PER_LOT', 'Fixed per lot')], default='PERCENT', max_length=20)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher matches first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.ForeignKey(blank=True, help_text='Empty = all account types.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ib_matrix_rules', to='admin_panel.tradingaccounttype')),
                ('ib_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_rules', to='ib.iblevel')),
                ('symbol_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ib_matrix_rules', to='admin_panel.symbolgroup')),
                ('trading_symbol', models.ForeignKey(blank=True, help_text='If set, applies only to this symbol (symbol-level override).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ib_matrix_symbol_overrides', to='admin_panel.tradingsymbol')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
