# Generated by Django 6.0.3 on 2026-04-06 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_crm_group_symbol_sync'),
        ('admin_panel', '0061_crm_group_symbol_sync'),
        ('ib', '0007_ib_levels_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibcommissionmatrixrule',
            name='matrix_symbol_name',
            field=models.CharField(blank=True, default='', help_text='Exact instrument (e.g. EURUSD). Empty = all symbols under mt5_crm_group.', max_length=64),
        ),
        migrations.AddField(
            model_name='ibcommissionmatrixrule',
            name='mt5_crm_group',
            field=models.ForeignKey(blank=True, help_text="CRM group (Group Management). When set, rule applies to this group's synced symbol universe.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ib_matrix_rules', to='accounts.mt5group'),
        ),
        migrations.AlterField(
            model_name='ibcommissionmatrixrule',
            name='trading_symbol',
            field=models.ForeignKey(blank=True, help_text='Legacy: TradingSymbol row. Prefer mt5_crm_group + matrix_symbol_name for platform-synced symbols.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ib_matrix_symbol_overrides', to='admin_panel.tradingsymbol'),
        ),
    ]
