# Generated by Django 5.2.14 on 2026-06-17 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0082_alter_adminauthbrandingsettings_logo_and_more'),
        ('ib', '0008_crm_group_symbol_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ibcommissionsettings',
            name='enable_withdraw_bank',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ibcommissionsettings',
            name='enable_withdraw_crypto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ibcommissionsettings',
            name='enable_withdraw_internal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ibcommissionsettings',
            name='enable_withdraw_manual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ibprofile',
            name='link_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProcessedMT5Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('login_id', models.CharField(db_index=True, max_length=64)),
                ('symbol', models.CharField(max_length=32)),
                ('volume_lots', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_time', models.DateTimeField(db_index=True)),
                ('account_group', models.CharField(max_length=120)),
                ('rebate_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rebate_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ib_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_deals', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ib.ibplan')),
            ],
            options={
                'ordering': ['-close_time'],
            },
        ),
        migrations.CreateModel(
            name='IBPlanSymbolRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('rebate_per_lot', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('account_type', models.ForeignKey(blank=True, help_text='Optional account type mapping for custom rebates per account type.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_symbol_rebates', to='admin_panel.tradingaccounttype')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_rebates', to='ib.ibplan')),
            ],
            options={
                'unique_together': {('plan', 'symbol', 'account_type')},
            },
        ),
    ]
