# Generated by Django 6.0.5 on 2026-07-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib', '0009_ibcommissionsettings_enable_withdraw_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibprofile',
            name='assigned_rebate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Assigned rebate per lot', max_digits=12),
        ),
    ]
