# Generated by Django 5.2.14 on 2026-07-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib', '0010_ibprofile_assigned_rebate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibprofile',
            name='assigned_rebate',
        ),
        migrations.RemoveField(
            model_name='ibprofile',
            name='ib_type',
        ),
        migrations.RemoveField(
            model_name='ibprofile',
            name='master_ib',
        ),
        migrations.RemoveField(
            model_name='ibprofile',
            name='sub_ib_commission_percent',
        ),
    ]
