# Generated by Django 6.0.3 on 2026-03-25 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('master_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copier_master_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CopierFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_risk_multiplier', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copier_followed_accounts', to=settings.AUTH_USER_MODEL)),
                ('copy_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='copier.copytradingaccount')),
            ],
            options={
                'unique_together': {('copy_account', 'follower')},
            },
        ),
    ]
