# Generated by Django 6.0.3 on 2026-03-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_referral_code_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='bank_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='swift_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='document',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
