# Generated by Django 6.0.3 on 2026-03-26 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_management_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='investor_password_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
