# Generated by Django 6.0.3 on 2026-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mt5_investor_credit_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='account_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='deposit_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='trading_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='withdraw_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
