# Generated by Django 6.0.3 on 2026-03-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_withdraw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
