# Generated by Django 6.0.3 on 2026-03-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_kycaddress_kycidentity_verifiedbankaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedbankaccount',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc/bank/'),
        ),
    ]
