# Generated by Django 6.0.3 on 2026-03-29 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_enterprise_and_user_totp'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycidentity',
            name='full_name_on_document',
            field=models.CharField(blank=True, default='', help_text='Legal name as shown on ID (used for admin KYC name matching).', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_approvals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('UTILITY_BILL', 'Utility Bill'), ('PROOF_OF_ADDRESS', 'Proof of Address'), ('SELFIE', 'Selfie / Liveness'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
