# Generated by Django 6.0.3 on 2026-03-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_kyc_email_symbols_ib_matrix'),
        ('admin_panel', '0022_kyc_email_symbols_ib_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5group',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mt5_groups', to='admin_panel.tradingaccounttype'),
        ),
        migrations.AddField(
            model_name='mt5group',
            name='commission_per_lot',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='mt5group',
            name='crm_group_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='mt5group',
            name='enable_crm_commission_testing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mt5group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
