# Generated by Django 6.0.3 on 2026-03-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_mt5group_account_type_mt5group_commission_per_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5group',
            name='commission_per_lot',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
