# Generated by Django 6.0.3 on 2026-04-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_mt5group_remove_legacy_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mt5group',
            options={'verbose_name': 'Broker group', 'verbose_name_plural': 'Broker groups'},
        ),
    ]
