# Generated by Django 6.0.3 on 2026-04-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_bonus_template_system'),
        ('admin_panel', '0048_bonus_template_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='bonus_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_bonuses', to='admin_panel.bonustemplate'),
        ),
        migrations.AlterField(
            model_name='mt5group',
            name='crm_group_name',
            field=models.CharField(blank=True, default='', help_text='Display name in CRM (e.g. Standard, ECN, Pro).', max_length=120),
        ),
        migrations.AlterField(
            model_name='mt5group',
            name='name',
            field=models.CharField(help_text='Exact MT5 group name on the server (e.g. STD-1, ECN-1).', max_length=120, unique=True),
        ),
    ]
