# Generated by Django 6.0.3 on 2026-04-03 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_client_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5account',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_accounts', to='accounts.mt5group'),
        ),
    ]
