# Generated by Django 6.0.3 on 2026-04-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_mt5group_match_trader_broker_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5group',
            name='name',
            field=models.CharField(help_text='Internal unique key / MT5 server group string when platform is MT5.', max_length=120, unique=True),
        ),
    ]
