# Generated by Django 6.0.3 on 2026-04-07 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_crm_group_symbol_sync'),
        ('admin_panel', '0063_crm_sales_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='admin_panel.crmdepartment'),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_via_sales_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SALES_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_registered_via_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('IB', 'IB'), ('CLIENT', 'Client'), ('TRADER', 'Trader'), ('BANKER', 'Banker'), ('COPIER', 'Copier'), ('SALES_MANAGER', 'Sales Manager')], default='CLIENT', max_length=20),
        ),
    ]
