# Generated by Django 6.0.3 on 2026-04-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_repair_user_crm_department_columns'),
        ('admin_panel', '0064_crm_roles_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_role',
            field=models.ForeignKey(blank=True, help_text='CRM permission template (folders: KYC, Finance, Sales, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='admin_panel.crmrole'),
        ),
    ]
