# Generated by Django 6.0.3 on 2026-04-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_verifiedcryptoaddress_wallet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiedbankaccount",
            name="branch",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional branch / location.",
                max_length=120,
            ),
        ),
    ]
