# Generated by Django 6.0.5 on 2026-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_verifiedbankaccount_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5group',
            name='platform',
            field=models.CharField(choices=[('MT5', 'MT5'), ('MATCH_TRADER', 'Match-Trader'), ('X9_TRADER', 'X9 Trader')], db_index=True, default='MT5', help_text='Trading platform this row maps to.', max_length=32),
        ),
        migrations.AddField(
            model_name='mt5group',
            name='platform_group_name',
            field=models.CharField(blank=True, default='', help_text='Exact group name on the platform (from live API / synced catalog).', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('IB', 'IB'), ('CLIENT', 'Client'), ('TRADER', 'Trader'), ('BANKER', 'Banker'), ('COPIER', 'Copier'), ('SALES_MANAGER', 'Sales Manager'), ('MANAGER', 'Account Manager')], default='CLIENT', max_length=20),
        ),
    ]
