# Generated by Codex on 2026-06-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_mt5group_platform_mt5group_platform_group_name_and_more"),
        ("admin_panel", "0076_remove_whitelist_treasury_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bonus",
            name="bonus_template",
        ),
    ]
