# Generated by Django 6.0.5 on 2026-06-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_bonus_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='mt5_account',
            field=models.ForeignKey(blank=True, help_text='The MT5 account this bonus was applied to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='accounts.mt5account'),
        ),
    ]
