# Generated by Django 5.2.13 on 2026-07-18 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_bonus_mt5_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5account',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mt5_accounts', to='accounts.mt5group'),
        ),
    ]
