# Generated by Django 6.0.8 on 2026-08-20 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_mt5group_brokerplatform_btrader'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('NO_LONGER_TRADING', 'No longer trading'), ('PRIVACY', 'Privacy concerns'), ('SWITCHING_BROKER', 'Switching to another broker'), ('DUPLICATE', 'Duplicate account'), ('UNHAPPY', 'Unhappy with the service'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grace_until', models.DateTimeField()),
                ('obligations_snapshot', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('staff_note', models.TextField(blank=True, default='')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'grace_until'], name='accounts_ac_status_5444f1_idx'), models.Index(fields=['user', 'status'], name='accounts_ac_user_id_de7947_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='uniq_pending_deletion_request_per_user')],
            },
        ),
    ]
