# Generated by Django 6.0.3 on 2026-03-28 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_login_max_attempts', models.PositiveIntegerField(default=10)),
                ('failed_login_lockout_seconds', models.PositiveIntegerField(default=900)),
                ('suspicious_failures_per_ip', models.PositiveIntegerField(default=8)),
                ('email_security_alerts', models.BooleanField(default=True)),
                ('withdrawal_submitted_alert', models.BooleanField(default=True)),
                ('login_new_device_alert', models.BooleanField(default=True)),
                ('risk_alert_threshold', models.PositiveIntegerField(default=75)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enterprise security settings',
            },
        ),
        migrations.CreateModel(
            name='ClientRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('exposure_limit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('exposure_current_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('booking', models.CharField(choices=[('A_BOOK', 'A-Book'), ('B_BOOK', 'B-Book')], default='B_BOOK', max_length=10)),
                ('monitoring_notes', models.TextField(blank=True, default='')),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client risk profile',
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(default='MEDIUM', max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('entity_type', models.CharField(db_index=True, max_length=60)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('channel', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('STAFF', 'Staff'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='enterprise__entity__c9ce91_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username_attempt', models.CharField(blank=True, default='', max_length=254)),
                ('success', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('suspicious', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip', 'created_at'], name='enterprise__ip_252bfc_idx')],
            },
        ),
    ]
