# Generated by Django 6.0.3 on 2026-03-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_screenshot',
            field=models.FileField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
