# Generated by Django 6.0.3 on 2026-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='api_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='charges',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('THIRD_PARTY', 'Third Party')], default='LOCAL', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='gateway_icons/'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='merchant_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='network',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_method',
            field=models.CharField(choices=[('BANK', 'Bank'), ('CRYPTO', 'Crypto'), ('WALLET', 'Wallet')], default='BANK', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='processing_time',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='scope',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('BOTH', 'Both')], default='BOTH', max_length=15),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='secret_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='wallet_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='webhook_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
