# Generated by Django 6.0.3 on 2026-03-26 18:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_internaltransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='BalanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entry_type', models.CharField(choices=[('WITHDRAW_HOLD', 'Withdraw Hold'), ('WITHDRAW_APPROVE', 'Withdraw Approve'), ('WITHDRAW_REJECT', 'Withdraw Reject'), ('TRANSFER_DEBIT', 'Transfer Debit'), ('TRANSFER_CREDIT', 'Transfer Credit')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('wallet_before', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('wallet_after', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pending_before', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pending_after', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('trading_before', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('trading_after', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
