# Generated by Django 6.0.3 on 2026-04-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_paymentgateway_deposit_type_and_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_demo_ledger',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, row is virtual/demo-only and excluded from real-money totals and client financial history.'),
        ),
    ]
