# Generated by Django 6.0.3 on 2026-04-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_is_demo_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
