# Generated by Django 6.0.3 on 2026-04-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_transaction_reject_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balanceledger",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("WITHDRAW_HOLD", "Withdraw Hold"),
                    ("WITHDRAW_APPROVE", "Withdraw Approve"),
                    ("WITHDRAW_REJECT", "Withdraw Reject"),
                    ("deposit_approve", "Deposit Approve"),
                    ("deposit_reject", "Deposit Reject"),
                    ("TRANSFER_DEBIT", "Transfer Debit"),
                    ("TRANSFER_CREDIT", "Transfer Credit"),
                ],
                max_length=30,
            ),
        ),
    ]
