# Generated by Django 6.0.5 on 2026-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_match2pay_expired_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='allowed_account_types',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='country_filters',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='custom_fields',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='first_time_deposit_only',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='flag_high_value',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='flag_problem_user',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='flag_vip',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='flag_watch_list',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='instruction_steps',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='integration_mode',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='kyc_level',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='require_transaction_id',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='risk_chargeback',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='risk_fraud',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='risk_kyc',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='risk_pep',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='risk_suspicious',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='risk_trading',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='risk_withdrawal',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='third_party_provider',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='user_fields',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_snapshot_wallet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User wallet_balance immediately after this withdrawal hold was placed.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_demo_ledger',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, row is virtual/demo-only and excluded from real-money totals.'),
        ),
    ]
