# Generated by Django 5.2.14 on 2026-07-21 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_ticket', models.CharField(db_index=True, max_length=64, unique=True)),
                ('order_ticket', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('position_ticket', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('login', models.CharField(db_index=True, max_length=64)),
                ('symbol', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('action', models.IntegerField(help_text='MT5 Deal Action (0=Buy, 1=Sell, etc.)')),
                ('entry_type', models.IntegerField(help_text='MT5 Deal Entry (0=In, 1=Out, etc.)')),
                ('volume', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('swap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('time', models.DateTimeField(db_index=True)),
                ('time_msc', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mt5_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MT5 Deal',
                'verbose_name_plural': 'MT5 Deals',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['login', 'time'], name='mt5_integra_login_4c50f0_idx'), models.Index(fields=['symbol', 'time'], name='mt5_integra_symbol_cefe26_idx')],
            },
        ),
    ]
